using VerifyCS =
    Converg.Generator.Tests.CSharpSourceGeneratorVerifier<Converg.Generator.FluentFactoryGenerator>;

namespace Converg.Generator.Tests;

/// <summary>
/// Tests for <c>[FluentFactory]</c> applied to types nested inside other types.
/// The generator must wrap the generated partial class inside the containing type hierarchy.
/// </summary>
public class NestedFactoryTests
{
    private const string SourceFile = "Source.cs";

    /// <summary>
    /// Verifies that when a <c>[FluentFactory]</c> is declared as a nested type inside another class,
    /// the generated partial class is correctly wrapped inside the containing type declaration.
    /// Without this fix, the generator emits <c>partial class Factory</c> at namespace level,
    /// which creates a new unrelated type instead of extending the nested factory.
    /// </summary>
    [Fact]
    internal async Task Should_wrap_generated_factory_in_containing_type_when_factory_is_nested()
    {
        const string code =
            """
            using Converg.Generator;

            namespace Test;

            public partial class Outer
            {
                [FluentFactory]
                public static partial class Factory;
            }

            public class Target
            {
                [FluentConstructor(typeof(Outer.Factory), CreateMethod = CreateMethod.None)]
                public Target(string name)
                {
                    Name = name;
                }

                public string Name { get; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                public partial class Outer
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("Converg", "1.0.0.0")]
                    public static partial class Factory
                    {
                        /// <summary>
                        ///     <seealso cref="Test.Target"/>
                        /// </summary>
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::Test.Target WithName(in string name)
                        {
                            return new global::Test.Target(name);
                        }
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Outer.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that deeply nested factory types (multiple levels of nesting) are correctly
    /// wrapped in the full containing type hierarchy.
    /// </summary>
    [Fact]
    internal async Task Should_wrap_generated_factory_in_deeply_nested_containing_types()
    {
        const string code =
            """
            using Converg.Generator;

            namespace Test;

            public partial class Level1
            {
                public partial class Level2
                {
                    [FluentFactory]
                    public static partial class Factory;
                }
            }

            public class Target
            {
                [FluentConstructor(typeof(Level1.Level2.Factory), CreateMethod = CreateMethod.None)]
                public Target(int value)
                {
                    Value = value;
                }

                public int Value { get; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                public partial class Level1
                {
                    public partial class Level2
                    {
                        [global::System.CodeDom.Compiler.GeneratedCode("Converg", "1.0.0.0")]
                        public static partial class Factory
                        {
                            /// <summary>
                            ///     <seealso cref="Test.Target"/>
                            /// </summary>
                            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                            public static global::Test.Target WithValue(in int value)
                            {
                                return new global::Test.Target(value);
                            }
                        }
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Level1.Level2.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
