using Microsoft.CodeAnalysis.Testing;
using Xunit;
using VerifyCS = Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

// Record-replay methodology: expected strings are captured by running each test with a
// deliberately wrong expected string (e.g., "TO-BE-CAPTURED"), observing the verifier's diff
// in the failure message, copying the "actual" (+) lines verbatim, and replacing $$VERSION$$
// for the hardcoded assembly version. Do not hand-write expected strings — the verifier's
// normalisation rules (line endings, trailing whitespace) are tricky.
//
// All fixtures import the required namespaces in the code string; the generated output uses
// global:: prefixes so no imports are needed in the generated source. The test compilation
// uses a global 'using System.Linq' (added by CSharpSourceGeneratorVerifier) so that
// ImmutableArray<T>.ToArray() resolves via the LINQ extension method.
public class AccumulatorStepGenerationTests
{
    // ── GEN-01: AddX returns same accumulator step type for chaining ─────────

    /// <summary>
    /// GEN-01: A single IList&lt;string&gt; collection parameter produces an accumulator struct with an
    /// AddItem method whose return type is the same accumulator struct (self-chaining).
    /// Pinned assertion: the method signature is
    ///   public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
    /// </summary>
    [Fact]
    internal async Task GEN_01_AddX_returns_same_accumulator_step_for_chaining()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-01 guard: AddItem return type is global::Test.Accumulator_0__Test_Builder (self-return).
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02a: IEnumerable<T> terminal uses field directly (identity conversion) ──

    /// <summary>
    /// GEN-02a: Declared type IEnumerable&lt;string&gt; — terminal passes the ImmutableArray&lt;string&gt;
    /// field directly without calling .ToArray() (identity conversion per RESEARCH.md Pattern 5).
    /// </summary>
    [Fact]
    internal async Task GEN_02a_IEnumerable_terminal_uses_field_directly()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IEnumerable<string> items) { }
            }
            """;

        // GEN-02a guard: terminal body passes this._items__parameter directly (no .ToArray()).
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02b: IList<T> terminal uses .ToArray() ────────────────────────────

    /// <summary>
    /// GEN-02b: Declared type IList&lt;string&gt; — terminal converts via .ToArray().
    /// (Identical fixture to GEN-01; pinned separately for explicit GEN-02b coverage.)
    /// </summary>
    [Fact]
    internal async Task GEN_02b_IList_terminal_uses_ToArray()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-02b guard: terminal body calls this._items__parameter.ToArray().
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02c: T[] terminal uses .ToArray() ────────────────────────────────

    /// <summary>
    /// GEN-02c: Declared type string[] — terminal converts via .ToArray().
    /// </summary>
    [Fact]
    internal async Task GEN_02c_Array_terminal_uses_ToArray()
    {
        const string code = """
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] string[] items) { }
            }
            """;

        // GEN-02c guard: terminal body calls this._items__parameter.ToArray() for T[].
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02d: ICollection<T> uses .ToArray() ───────────────────────────────

    /// <summary>
    /// GEN-02d: Declared type ICollection&lt;int&gt; — terminal converts via .ToArray().
    /// </summary>
    [Fact]
    internal async Task GEN_02d_ICollection_terminal_uses_ToArray()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] ICollection<int> items) { }
            }
            """;

        // GEN-02d guard: terminal body calls this._items__parameter.ToArray() for ICollection<T>.
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<int> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<int>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<int> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in int item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02e: IReadOnlyCollection<T> uses field directly ─────────────────

    /// <summary>
    /// GEN-02e: Declared type IReadOnlyCollection&lt;string&gt; — identity conversion (no .ToArray()).
    /// </summary>
    [Fact]
    internal async Task GEN_02e_IReadOnlyCollection_terminal_uses_field_directly()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IReadOnlyCollection<string> items) { }
            }
            """;

        // GEN-02e guard: terminal body passes this._items__parameter directly (no .ToArray()).
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-02f: IReadOnlyList<T> uses field directly ────────────────────────

    /// <summary>
    /// GEN-02f: Declared type IReadOnlyList&lt;string&gt; — identity conversion (no .ToArray()).
    /// </summary>
    [Fact]
    internal async Task GEN_02f_IReadOnlyList_terminal_uses_field_directly()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IReadOnlyList<string> items) { }
            }
            """;

        // GEN-02f guard: terminal body passes this._items__parameter directly (no .ToArray()).
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-03: readonly struct + ImmutableArray field guarantee branch safety ─

    /// <summary>
    /// GEN-03: Structural safety check — the accumulator struct is declared as 'readonly struct'
    /// AND the accumulator field is ImmutableArray&lt;string&gt;. These two language properties
    /// guarantee that two chain variables branching at the same accumulator struct instance
    /// accumulate independent items (each AddX call returns a new copy via ImmutableArray.Add).
    /// The test verifies the shape; branching safety is a language-level consequence.
    /// (Uses identical fixture to GEN-01/GEN-02b; pinned separately for explicit GEN-03 coverage.)
    /// </summary>
    [Fact]
    internal async Task GEN_03_branching_at_accumulator_is_structurally_safe()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-03 guard: struct is 'public readonly struct Accumulator_0__Test_Builder'
        // and field is 'ImmutableArray<string>' — these together guarantee branch independence.
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-04: accumulator field initialised to ImmutableArray<T>.Empty ─────

    /// <summary>
    /// GEN-04: The entry constructor initialises every accumulator field to
    /// ImmutableArray&lt;T&gt;.Empty (Pitfall 1 guard — prevents shared-state bugs on struct copy).
    /// Pinned assertion: entry ctor body contains
    ///   this._items__parameter = global::System.Collections.Immutable.ImmutableArray&lt;string&gt;.Empty;
    /// (Uses identical fixture to GEN-01; pinned separately for explicit GEN-04 coverage.)
    /// </summary>
    [Fact]
    internal async Task GEN_04_accumulator_field_initialized_to_Empty()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-04 guard: entry constructor body contains
        //   this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-05: AddX parameter type is element type, not collection type ──────

    /// <summary>
    /// GEN-05: The AddItem method's parameter type is 'in string item', NOT
    /// 'in global::System.Collections.Generic.IList&lt;string&gt;' (Pitfall 3 guard).
    /// Verified by inspecting the full generated source for the IList&lt;string&gt; fixture.
    /// (Uses identical fixture to GEN-01; pinned separately for explicit GEN-05 coverage.)
    /// </summary>
    [Fact]
    internal async Task GEN_05_AddX_parameter_is_element_type_not_collection_type()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-05 guard: AddItem parameter is 'in string item', not 'in IList<string> items'.
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-06: struct is readonly and all methods carry AggressiveInlining ───

    /// <summary>
    /// GEN-06: The accumulator struct is unconditionally declared as 'public readonly struct
    /// Accumulator_0__...' and every method carries [MethodImpl(AggressiveInlining)].
    /// Pitfall 5 guard — ReadOnlyKeyword is emitted unconditionally by AccumulatorStepDeclaration.
    /// (Uses identical fixture to GEN-01; pinned separately for explicit GEN-06 coverage.)
    /// </summary>
    [Fact]
    internal async Task GEN_06_struct_is_readonly_and_methods_have_AggressiveInlining()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target([FluentCollectionMethod] IList<string> items) { }
            }
            """;

        // GEN-06 guard: 'public readonly struct Accumulator_0__Test_Builder'
        // and every method has [MethodImpl(AggressiveInlining)].
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── Optional: multiple collection parameters on same target ───────────────

    /// <summary>
    /// Multiple collection parameters on the same constructor produce a single accumulator struct
    /// with multiple AddX methods (one per parameter), each updating its own field while
    /// forwarding all other fields unchanged. Verifies RESEARCH.md Open Question 2.
    /// </summary>
    [Fact]
    internal async Task Multiple_collection_parameters_same_step()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target(
                    [FluentCollectionMethod] IList<string> tags,
                    [FluentCollectionMethod] IList<int> counts) { }
            }
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _tags__parameter;
                    private readonly global::System.Collections.Immutable.ImmutableArray<int> _counts__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._tags__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                        this._counts__parameter = global::System.Collections.Immutable.ImmutableArray<int>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> tags, in global::System.Collections.Immutable.ImmutableArray<int> counts)
                    {
                        this._tags__parameter = tags;
                        this._counts__parameter = counts;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddTag(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._tags__parameter.Add(item), this._counts__parameter);
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddCount(in int item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._tags__parameter, this._counts__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._tags__parameter.ToArray(), this._counts__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── Optional: mixed regular + collection parameters ───────────────────────

    /// <summary>
    /// A constructor with one regular parameter plus one collection parameter produces:
    ///   - A Step_0__ struct with a WithName method and a BuildTarget() transition method
    ///   - An Accumulator_1__ struct with AddItem + CreateTarget() terminal
    ///   - No terminal method on Step_0__ (RESEARCH.md Open Question 3 — terminal on accumulator only)
    /// Verifies the AccumulatorTransitionMethod architecture end-to-end.
    /// </summary>
    [Fact]
    internal async Task Collection_plus_regular_parameter()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target(string name, [FluentCollectionMethod] IList<string> items) { }
            }
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Target"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_1__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_1__Test_Builder(this._name__parameter);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_1__Test_Builder
                {
                    private readonly string _name__parameter;
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _items__parameter;
                    public Accumulator_1__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                        this._items__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_1__Test_Builder(in string name, in global::System.Collections.Immutable.ImmutableArray<string> items)
                    {
                        this._name__parameter = name;
                        this._items__parameter = items;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_1__Test_Builder AddItem(in string item)
                    {
                        return new global::Test.Accumulator_1__Test_Builder(this._name__parameter, this._items__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._name__parameter, this._items__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    // ── GEN-07: Generic target threads type parameters onto accumulator struct ──

    /// <summary>
    /// GEN-07: When a generic target (e.g., <c>Train&lt;TEngine&gt;</c>) forwards a type parameter
    /// field into the accumulator step, the emitted <c>Accumulator_X</c> struct must declare the
    /// same generic type parameter list and constraints, and both the transition method return type
    /// and the terminal return type must reference the generic accumulator/target with the
    /// type argument threaded through. Regression guard for build-time <c>CS0246</c> when the
    /// accumulator struct was emitted non-generic while referencing <c>TEngine</c> in field/method
    /// signatures.
    /// </summary>
    [Fact]
    internal async Task GEN_07_Generic_target_threads_type_parameter_onto_accumulator()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public interface IEngine { }
            public class Wheel { }
            [FluentTarget(typeof(Builder))]
            public record Train<TEngine>(
                [FluentMethod("WithEngine")] TEngine Engine,
                [FluentCollectionMethod] IEnumerable<Wheel> Wheels)
                where TEngine : IEngine;
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Train{TEngine}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder<TEngine> WithEngine<TEngine>(in TEngine engine)
                        where TEngine : global::Test.IEngine
                    {
                        return new global::Test.Step_0__Test_Builder<TEngine>(engine);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Train{TEngine}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder<TEngine> where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    internal Step_0__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Train{TEngine}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_1__Test_Builder<TEngine> BuildTrain()
                    {
                        return new global::Test.Accumulator_1__Test_Builder<TEngine>(this._engine__parameter);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_1__Test_Builder<TEngine>
                    where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    private readonly global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel> _wheels__parameter;
                    public Accumulator_1__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel>.Empty;
                    }

                    private Accumulator_1__Test_Builder(in TEngine engine, in global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel> wheels)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = wheels;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_1__Test_Builder<TEngine> AddWheel(in global::Test.Wheel item)
                    {
                        return new global::Test.Accumulator_1__Test_Builder<TEngine>(this._engine__parameter, this._wheels__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Train<TEngine> CreateTrain()
                    {
                        return new global::Test.Train<TEngine>(this._engine__parameter, this._wheels__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }
}
