using Microsoft.CodeAnalysis.Testing;
using Xunit;
using VerifyCS = Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

// Scenario: a collection element type carries a type parameter that is not yet resolved
// by the forwarded/threaded parameters leading into the accumulator. Example:
//   class Train<TEngine, T>(TEngine engine, [FluentCollectionMethod] IEnumerable<Wheel<T>> wheels)
// At the point the accumulator is entered via WithTrainEngine, TEngine is bound but T is not.
// T enters the system only when the first AddWheel argument supplies it.
//
// Design:
//   - Pre-resolution step: same index, fewer generics. Forwarded fields only (no collection
//     field yet). Exposes a generic AddWheel<T>(in Wheel<T>) that transitions to the
//     resolved step, and a generic terminal CreateVehicles_Train<T>() for the empty-chain case.
//   - Resolved step: same index, extra generic for the newly bound parameter. Holds the
//     ImmutableArray<Wheel<T>> field, a non-generic AddWheel(in Wheel<T>), and the
//     non-generic terminal.
// The two structs share a base name and differ only in arity so both can coexist.
public class AccumulatorUnresolvedGenericTests
{
    [Fact]
    internal async Task Should_split_accumulator_when_collection_element_carries_unresolved_generic()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;

            public interface IEngine;
            public record Wheel<T>;

            [FluentRoot]
            public partial class Builder;

            [FluentTarget<Builder>]
            public partial record Train<TEngine, T>(
                [FluentMethod("WithEngine")] TEngine Engine,
                [FluentCollectionMethod] IEnumerable<Wheel<T>> Wheels)
                where TEngine : IEngine;
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Train{TEngine, T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder<TEngine> WithEngine<TEngine>(in TEngine engine)
                        where TEngine : global::Test.IEngine
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine>(engine);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder<TEngine, T>
                    where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    private readonly global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>> _wheels__parameter;
                    public Accumulator_0__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in TEngine engine, in global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>> wheels)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = wheels;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder<TEngine, T> AddWheel(in global::Test.Wheel<T> item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter, this._wheels__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Train<TEngine, T> CreateTrain()
                    {
                        return new global::Test.Train<TEngine, T>(this._engine__parameter, this._wheels__parameter);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder<TEngine>
                    where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    public Accumulator_0__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder<TEngine, T> AddWheel<T>(in global::Test.Wheel<T> item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter).AddWheel(item);
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Train<TEngine, T> CreateTrain<T>()
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter).CreateTrain();
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_support_empty_chain_via_generic_terminal_on_pre_step()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;

            public interface IEngine;
            public class TrainEngine : IEngine;
            public record Wheel<T>;

            [FluentRoot]
            public partial class Builder;

            [FluentTarget<Builder>]
            public partial record Train<TEngine, T>(
                [FluentMethod("WithEngine")] TEngine Engine,
                [FluentCollectionMethod] IEnumerable<Wheel<T>> Wheels)
                where TEngine : IEngine;

            // Consumer proof the generic terminal is callable with explicit type arg:
            //   Train<TrainEngine, int> train = Builder.WithEngine(new TrainEngine()).CreateTrain<int>();
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Train{TEngine, T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder<TEngine> WithEngine<TEngine>(in TEngine engine)
                        where TEngine : global::Test.IEngine
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine>(engine);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder<TEngine, T>
                    where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    private readonly global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>> _wheels__parameter;
                    public Accumulator_0__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in TEngine engine, in global::System.Collections.Immutable.ImmutableArray<global::Test.Wheel<T>> wheels)
                    {
                        this._engine__parameter = engine;
                        this._wheels__parameter = wheels;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder<TEngine, T> AddWheel(in global::Test.Wheel<T> item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter, this._wheels__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Train<TEngine, T> CreateTrain()
                    {
                        return new global::Test.Train<TEngine, T>(this._engine__parameter, this._wheels__parameter);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder<TEngine>
                    where TEngine : global::Test.IEngine
                {
                    private readonly TEngine _engine__parameter;
                    public Accumulator_0__Test_Builder(in TEngine engine)
                    {
                        this._engine__parameter = engine;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder<TEngine, T> AddWheel<T>(in global::Test.Wheel<T> item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter).AddWheel(item);
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Train<TEngine, T> CreateTrain<T>()
                    {
                        return new global::Test.Accumulator_0__Test_Builder<TEngine, T>(this._engine__parameter).CreateTrain();
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_diagnose_when_multiple_collections_carry_disjoint_unresolved_generics()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;

            public interface IEngine;
            public record Wheel<T>;
            public record Brake<U>;

            [FluentRoot]
            public partial class Builder;

            [FluentTarget<Builder>]
            public partial record Train<TEngine, T, U>(
                [FluentMethod("WithEngine")] TEngine Engine,
                [FluentCollectionMethod] IEnumerable<Wheel<T>> Wheels,
                [FluentCollectionMethod] IEnumerable<Brake<U>> Brakes)
                where TEngine : IEngine;
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError("CVJG0054")
                        .WithSpan("/0/Test1.cs", 12, 23, 12, 28)
                        .WithArguments("Test.Train<TEngine, T, U>", "T, U")
                }
            }
        };
        await test.RunAsync();
    }
}
