using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// BACK-02 byte-identical snapshot tests.
/// These tests pin the exact generated output for representative pre-Phase-21 fixtures.
/// If Phase 21 changes introduce any whitespace or ordering drift, these tests catch it
/// even if structural tests (which only check shape) would still pass.
///
/// Recording methodology: the expected strings below were captured by running each test with
/// a placeholder string, observing the verifier's diff in the failure message, copying the
/// "actual" lines verbatim (replacing the hardcoded version number with the $$VERSION$$
/// placeholder), and confirming the test passes on re-run.
/// </summary>
public class BackwardCompatibilitySnapshotTests
{
    private const string SourceFile = "Source.cs";

    /// <summary>
    /// Fixture A: A two-parameter constructor on a plain class.
    /// Exercises the standard parameter-first trie path with DynamicSuffix terminal (CreateCat).
    /// No [FluentCollectionMethod] anywhere — confirms Phase 21 collection scaffolding
    /// does not perturb output for code that never uses the new attribute.
    /// Snapshot covers: root entry method, two chained step structs, terminal method.
    /// </summary>
    [Fact]
    internal async Task Representative_fixture_produces_byte_identical_output()
    {
        const string code = """
            using Converj.Generator;

            namespace Animals;

            [FluentRoot]
            public static partial class AnimalFactory { }

            public class Cat
            {
                [FluentTarget(typeof(AnimalFactory))]
                public Cat(string name, int age) { }
            }
            """;

        // Record-replay: snapshot captured on first run; $$VERSION$$ replaces the hardcoded assembly version.
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Animals
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class AnimalFactory
                {
                    /// <summary>
                    ///     <seealso cref="Animals.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Animals.Step_0__Animals_AnimalFactory WithName(in string name)
                    {
                        return new global::Animals.Step_0__Animals_AnimalFactory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Animals.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Animals_AnimalFactory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Animals_AnimalFactory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Animals.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Animals.Step_1__Animals_AnimalFactory WithAge(in int age)
                    {
                        return new global::Animals.Step_1__Animals_AnimalFactory(this._name__parameter, age);
                    }
                }

                /// <summary>
                ///     <seealso cref="Animals.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Animals_AnimalFactory
                {
                    private readonly string _name__parameter;
                    private readonly int _age__parameter;
                    internal Step_1__Animals_AnimalFactory(in string name, in int age)
                    {
                        this._name__parameter = name;
                        this._age__parameter = age;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Animals.Cat.Cat(string name, int age).
                    ///
                    ///     <seealso cref="Animals.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Animals.Cat CreateCat()
                    {
                        return new global::Animals.Cat(this._name__parameter, this._age__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Animals.AnimalFactory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    /// <summary>
    /// Fixture B: A single-parameter constructor on a class with no collection attributes.
    /// Exercises the minimal single-step chain path with DynamicSuffix terminal (CreateWidget).
    /// Specifically confirms that introducing the Phase 21 analyzer and the CollectionParameters
    /// carrier does NOT perturb output for code that doesn't use [FluentCollectionMethod] at all.
    /// Snapshot covers: root entry method, one step struct, terminal method.
    /// </summary>
    [Fact]
    internal async Task Fixture_with_noncollection_parameter_and_no_attribute_produces_byte_identical_output()
    {
        const string code = """
            using Converj.Generator;

            namespace Widgets;

            [FluentRoot]
            public static partial class WidgetFactory { }

            public class Widget
            {
                [FluentTarget(typeof(WidgetFactory))]
                public Widget(string name) { }
            }
            """;

        // Record-replay: snapshot captured on first run; $$VERSION$$ replaces the hardcoded assembly version.
        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Widgets
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class WidgetFactory
                {
                    /// <summary>
                    ///     <seealso cref="Widgets.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Widgets.Step_0__Widgets_WidgetFactory WithName(in string name)
                    {
                        return new global::Widgets.Step_0__Widgets_WidgetFactory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Widgets.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Widgets_WidgetFactory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Widgets_WidgetFactory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Widgets.Widget.Widget(string name).
                    ///
                    ///     <seealso cref="Widgets.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Widgets.Widget CreateWidget()
                    {
                        return new global::Widgets.Widget(this._name__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Widgets.WidgetFactory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }
}
