using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class BugDiscoveryTests
{
    private const string SourceFile = "Source.cs";

    [Fact]
    internal async Task Should_allow_attribute_on_type_declaration_to_be_applied_to_all_constructors()
    {
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget))]
                public partial class MyBuildTarget
                {
                    public MyBuildTarget(int value) { }
                    public MyBuildTarget(string name) { }
                    public MyBuildTarget(double amount) { }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_MyTarget WithValue(in int value)
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_MyTarget(value);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_1__Test_Namespace_MyTarget WithName(in string name)
                    {
                        return new global::Test.Namespace.Step_1__Test_Namespace_MyTarget(name);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_2__Test_Namespace_MyTarget WithAmount(in double amount)
                    {
                        return new global::Test.Namespace.Step_2__Test_Namespace_MyTarget(amount);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_MyTarget
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Namespace_MyTarget(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._value__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Namespace_MyTarget
                {
                    private readonly string _name__parameter;
                    internal Step_1__Test_Namespace_MyTarget(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(string name).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._name__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Namespace_MyTarget
                {
                    private readonly double _amount__parameter;
                    internal Step_2__Test_Namespace_MyTarget(in double amount)
                    {
                        this._amount__parameter = amount;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(double amount).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._amount__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_allow_attribute_on_type_declaration_to_be_overridden_by_attribute_for_specific_constructors()
    {
        const string source = """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget))]
                public partial class MyBuildTarget
                {
                    public MyBuildTarget(int value) { }
                    public MyBuildTarget(string name) { }

                    [FluentConstructor(typeof(MyTarget), CreateMethod = CreateMethod.None)]
                    public MyBuildTarget(double amount) { }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_MyTarget WithValue(in int value)
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_MyTarget(value);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_1__Test_Namespace_MyTarget WithName(in string name)
                    {
                        return new global::Test.Namespace.Step_1__Test_Namespace_MyTarget(name);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.MyBuildTarget WithAmount(in double amount)
                    {
                        return new global::Test.Namespace.MyBuildTarget(amount);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_MyTarget
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Namespace_MyTarget(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._value__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Namespace_MyTarget
                {
                    private readonly string _name__parameter;
                    internal Step_1__Test_Namespace_MyTarget(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(string name).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_create_method_name_and_no_create_method_are_used_together()
    {
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), CreateMethod = CreateMethod.None, CreateVerb = "New")]
                public partial record MyBuildTarget(int Value);
            }
            """;

        // Does not generate any code.
        await new VerifyCS.Test
        {
            TestState = { Sources = { (SourceFile, source) } },
            ExpectedDiagnostics =
            {
                DiagnosticResult.CompilerError("CVJG0010")
                    .WithSpan("Source.cs", 8, 6, 8, 95)
                    .WithMessage("CreateVerb cannot be used with CreateMethod.None"),
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_allow_multiple_fluent_constructor_attributes_with_different_create_method_names()
    {
        // Tests what happens when multiple FluentConstructor attributes have different CreateVerb values
        const string source = """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), CreateMethod = CreateMethod.Fixed, CreateVerb = "CreateFirst")]
                [FluentConstructor(typeof(MyTarget), CreateMethod = CreateMethod.Fixed, CreateVerb = "CreateSecond")]
                public partial record MyBuildTarget(int Value);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_MyTarget WithValue(in int value)
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_MyTarget(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_MyTarget
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Namespace_MyTarget(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(int Value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateFirst()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._value__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(int Value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget CreateSecond()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Theory]
    [ClassData(typeof(InvalidMethodNames))]
    public async Task Should_error_when_invalid_create_method_names(string invalidMethodName)
    {
        // Tests CreateVerb handling with edge case error values and putting red squiggles on them
        var createMethodNameArgument =
            $"""
             CreateVerb = "{invalidMethodName}"
             """;

        var source =
          $$"""
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), {{createMethodNameArgument}}, CreateMethod = CreateMethod.Fixed)]
                public partial record EmptyName(int Value);
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError("CVJG0007")
                        .WithSpan("Source.cs", 8, 42, 8, 42 + createMethodNameArgument.Length)
                        .WithMessage("CreateVerb must be a valid identifier")
                }
            }
        }.RunAsync();
    }

    [Theory][InlineData("_")]
    [InlineData("__")]
    [InlineData("_1")]
    [InlineData("MethodWith??")]
    [InlineData("Methoda�?")]
    [InlineData("Method_I")]
    [InlineData("GetS?F")]
    [InlineData("@class")] // Escaped keyword
    [InlineData("Method__With__Double__Underscores")]
    [InlineData("Create")]
    public async Task Should_error_when_duplicate_fluent_constructor_attributes_with_identical_parameters(
        string methodName)
    {
        // Tests what happens with completely identical FluentConstructor attributes
        var createMethodNameArgument =
            $"""
             CreateVerb = "{methodName}"
             """;

        var source =
          $$"""
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), {{createMethodNameArgument}})] // First occurrence
                [FluentConstructor(typeof(MyTarget), {{createMethodNameArgument}})] // Exact duplicate
                public partial record DuplicateAttributes(int Value);
            }
            """;

        await new VerifyCS.Test
        {
            TestState = { Sources = { (SourceFile, source) } },
            ExpectedDiagnostics =
            {
                DiagnosticResult.CompilerError("CVJG0008")
                    .WithSpan("Source.cs", 8, 42, 8, 42 + createMethodNameArgument.Length)
                    .WithSpan("Source.cs", 9, 42, 9, 42 + createMethodNameArgument.Length)
                    .WithMessage("Create method name must be unique")
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_allow_duplicates_method_names_located_on_different_decision_paths()
    {
        // Tests what happens with completely identical FluentConstructor attributes
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                // constructor with a string parameter
                [FluentConstructor(typeof(MyTarget))]
                public partial record MyRecordA(string Value);

                // constructor with an int parameter
                [FluentConstructor(typeof(MyTarget))]
                public partial record MyRecordB(int Value);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyRecordA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_MyTarget WithValue(in string value)
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_MyTarget(value);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyRecordB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_1__Test_Namespace_MyTarget WithValue(in int value)
                    {
                        return new global::Test.Namespace.Step_1__Test_Namespace_MyTarget(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyRecordA"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_MyTarget
                {
                    private readonly string _value__parameter;
                    internal Step_0__Test_Namespace_MyTarget(in string value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyRecordA.MyRecordA(string Value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyRecordA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyRecordA CreateMyRecordA()
                    {
                        return new global::Test.Namespace.MyRecordA(this._value__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyRecordB"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Namespace_MyTarget
                {
                    private readonly int _value__parameter;
                    internal Step_1__Test_Namespace_MyTarget(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyRecordB.MyRecordB(int Value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyRecordB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyRecordB CreateMyRecordB()
                    {
                        return new global::Test.Namespace.MyRecordB(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_fluent_factory_attribute_on_non_target_type()
    {
        // Tests what happens when FluentFactory is missing on referenced type
        const string fluentFactoryRootType = "typeof(MyTarget)";

        var source =
          $$"""
            using Converj.Generator;

            namespace Test.Namespace
            {
                // Missing [FluentFactory] attribute
                public partial class MyTarget;

                [FluentConstructor({{fluentFactoryRootType}})] // References type without FluentFactory
                public partial record InvalidTarget(int Value);
            }
            """;

        await new VerifyCS.Test
        {
            TestState = { Sources = { (SourceFile, source) } },
            ExpectedDiagnostics =
            {
                DiagnosticResult.CompilerError("CVJG0009")
                    .WithSpan("Source.cs", 8, 24, 8, 24 + fluentFactoryRootType.Length)
                    .WithMessage("FluentConstructor references type 'Test.Namespace.MyTarget' which does not have the FluentFactory attribute"),
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_empty_create_verb_with_fixed_create_method()
    {
        const string createVerbArgument = "CreateVerb = \"\"";

        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), CreateVerb = "", CreateMethod = CreateMethod.Fixed)]
                public partial record EmptyName(int Value);
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError("CVJG0007")
                        .WithSpan("Source.cs", 8, 42, 8, 42 + createVerbArgument.Length)
                        .WithMessage("CreateVerb must be a valid identifier")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_warn_when_empty_create_verb_with_none_create_method()
    {
        const string createVerbArgument = "CreateVerb = \"\"";

        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), CreateVerb = "", CreateMethod = CreateMethod.None)]
                public partial record EmptyName(int Value);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.EmptyName"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.EmptyName WithValue(in int value)
                    {
                        return new global::Test.Namespace.EmptyName(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning("CVJG0017")
                        .WithSpan("Source.cs", 8, 42, 8, 42 + createVerbArgument.Length)
                        .WithMessage("CreateVerb has no effect with CreateMethod.None")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_allow_empty_create_verb_with_dynamic_create_method()
    {
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentFactory]
                public partial class MyTarget;

                [FluentConstructor(typeof(MyTarget), CreateVerb = "", CreateMethod = CreateMethod.Dynamic)]
                public partial record MyBuildTarget(int Value);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyTarget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_MyTarget WithValue(in int value)
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_MyTarget(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_MyTarget
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Namespace_MyTarget(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.MyBuildTarget.MyBuildTarget(int Value).
                    ///
                    ///     <seealso cref="Test.Namespace.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.MyBuildTarget MyBuildTarget()
                    {
                        return new global::Test.Namespace.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Namespace.MyTarget.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_disambiguate_when_one_constructor_has_create_method_and_other_does_not()
    {
        const string source = """
            using System;
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Person
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Person(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }

                public class Company
                {
                    [FluentConstructor(typeof(Factory))]
                    public Company(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.Company"/>
                    ///     <seealso cref="MyNamespace.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Person WithName(in string name)
                    {
                        return new global::MyNamespace.Person(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Person
                {
                    /// <summary>
                    /// Creates a new instance using constructor MyNamespace.Company.Company(string name).
                    ///
                    ///     <seealso cref="MyNamespace.Company"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.Company CreateCompany()
                    {
                        return new global::MyNamespace.Company(this.Name);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
