using Microsoft.CodeAnalysis.Testing;
using VerifyCS = Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Tests that a collection parameter with both [FluentCollectionMethod] and [FluentMethod]
/// produces both <c>AddX(T item)</c> and <c>WithXs(IEnumerable&lt;T&gt; items)</c> methods on the
/// accumulator step — the core composability feature of Phase 23 Plan 02 (COMP-02).
/// </summary>
public class CollectionMethodBulkSetTests
{
    /// <summary>
    /// COMP-02: When a parameter carries both [FluentCollectionMethod] and [FluentMethod],
    /// the generated accumulator step exposes AddTag(string item) (existing Phase 22 behavior)
    /// AND WithTags(IEnumerable&lt;string&gt; items) (new bulk-append method) — both self-returning.
    /// The root Factory class exposes both BuildTarget() (parameterless) and WithTags(IEnumerable&lt;string&gt;)
    /// as entry points to the same accumulator step.
    /// </summary>
    [Fact]
    internal async Task COMP_02_accumulator_step_exposes_both_AddTag_and_WithTags_methods()
    {
        const string code = """
            using System.Collections.Generic;
            namespace Test;
            [FluentRoot]
            public static partial class Builder { }
            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target(
                    [FluentCollectionMethod, FluentMethod("WithTags")] IList<string> tags) { }
            }
            """;

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder WithTags(global::System.Collections.Generic.IEnumerable<string> items)
                    {
                        return new global::Test.Accumulator_0__Test_Builder().WithTags(items);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _tags__parameter;
                    public Accumulator_0__Test_Builder()
                    {
                        this._tags__parameter = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> tags)
                    {
                        this._tags__parameter = tags;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddTag(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._tags__parameter.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder WithTags(global::System.Collections.Generic.IEnumerable<string> items)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._tags__parameter.AddRange(items));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target(this._tags__parameter.ToArray());
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }
}
