using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Edge case tests for constructor chaining scenarios (CTOR-03, CTOR-04).
/// Verifies that the generator correctly handles constructors that use <c>this(...)</c>
/// initializers, producing fluent output based solely on the annotated constructor's
/// parameters — not on the initializer's argument details.
/// </summary>
public class ConstructorChainingTests
{
    /// <summary>
    /// CTOR-03: A class has two constructors where one chains to the other via <c>this(...)</c>.
    /// The [FluentConstructor] is placed on the chaining constructor (the one with MORE parameters).
    /// The generator should produce a 2-step fluent chain for the annotated constructor's parameters only.
    /// </summary>
    [Fact]
    internal async Task Should_generate_fluent_chain_when_constructor_chains_to_another_via_this()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public MyBuildTarget(int value, string name) : this(value)
                {
                    Name = name;
                }

                public int Value { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Factory(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithName(in string name)
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter, name);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// CTOR-03: A class has a 3-parameter constructor that chains to a 1-parameter constructor
    /// via <c>this(id)</c>. The [FluentConstructor] is on the 3-parameter constructor.
    /// The generator should produce a full 3-step chain based on all 3 parameters.
    /// </summary>
    [Fact]
    internal async Task Should_generate_three_step_chain_when_three_param_constructor_chains_to_one_param()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                public MyBuildTarget(int id)
                {
                    Id = id;
                }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public MyBuildTarget(int id, string name, bool active) : this(id)
                {
                    Name = name;
                    Active = active;
                }

                public int Id { get; set; }
                public string Name { get; set; }
                public bool Active { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_0__Test_Factory(id);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _id__parameter;
                    internal Step_0__Test_Factory(in int id)
                    {
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_1__Test_Factory(this._id__parameter, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    internal Step_1__Test_Factory(in int id, in string name)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithActive(in bool active)
                    {
                        return new global::Test.MyBuildTarget(this._id__parameter, this._name__parameter, active);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// CTOR-04: Same as the 3-parameter chaining test but the <c>this(...)</c> call uses a named
    /// argument (e.g., <c>this(id: id)</c>). The generator reads parameter metadata from
    /// <c>IMethodSymbol</c>, not initializer syntax, so the output must be identical to the
    /// positional-argument version.
    /// </summary>
    [Fact]
    internal async Task Should_generate_identical_output_when_this_initializer_uses_named_arguments()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                public MyBuildTarget(int id)
                {
                    Id = id;
                }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public MyBuildTarget(int id, string name, bool active) : this(id: id)
                {
                    Name = name;
                    Active = active;
                }

                public int Id { get; set; }
                public string Name { get; set; }
                public bool Active { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_0__Test_Factory(id);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _id__parameter;
                    internal Step_0__Test_Factory(in int id)
                    {
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_1__Test_Factory(this._id__parameter, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    internal Step_1__Test_Factory(in int id, in string name)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithActive(in bool active)
                    {
                        return new global::Test.MyBuildTarget(this._id__parameter, this._name__parameter, active);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// CTOR-04: Constructor <c>(string name, int id, bool active)</c> chains to a 2-parameter
    /// constructor via <c>this(active: active, id: id)</c> — reordered named arguments.
    /// The generator must follow the annotated constructor's parameter ORDER (name, id, active),
    /// not the initializer argument order, because it reads <c>IMethodSymbol</c> parameter metadata.
    /// </summary>
    [Fact]
    internal async Task Should_generate_chain_in_annotated_constructor_parameter_order_when_this_initializer_uses_reordered_named_arguments()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                public MyBuildTarget(int id, bool active)
                {
                    Id = id;
                    Active = active;
                }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public MyBuildTarget(string name, int id, bool active) : this(active: active, id: id)
                {
                    Name = name;
                }

                public string Name { get; set; }
                public int Id { get; set; }
                public bool Active { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, id);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _id__parameter;
                    internal Step_1__Test_Factory(in string name, in int id)
                    {
                        this._name__parameter = name;
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithActive(in bool active)
                    {
                        return new global::Test.MyBuildTarget(this._name__parameter, this._id__parameter, active);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Issue #15: Deep initializer chain resolution (3 levels).
    /// Ctor3(a, b, c) : this(a, b) -> Ctor2(a, b) : this(a) -> Ctor1(a) stores a in field.
    /// The generator must resolve storage transitively across multiple hops.
    ///
    /// Two [FluentConstructor] annotations make Widget a custom intermediate step at (name, size).
    /// The 2-param constructor uses CreateMethod.None so Widget itself becomes an ExistingTypeFluentStep.
    /// The generated partial Widget class has a WithVisible method whose arguments reference the
    /// resolved storage — this._name (field, via 2-hop chain) and this.Size (property, via 1-hop chain) —
    /// proving that the multi-hop initializer chain resolution actually affects the output.
    /// </summary>
    [Fact]
    internal async Task Should_resolve_storage_through_multi_hop_initializer_chain()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class Widget
            {
                private readonly string _name;

                public Widget(string name)
                {
                    _name = name;
                }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Widget(string name, int size) : this(name)
                {
                    Size = size;
                }

                [FluentConstructor(typeof(Factory))]
                public Widget(string name, int size, bool visible) : this(name, size)
                {
                    Visible = visible;
                }

                public string Name => _name;
                public int Size { get; set; }
                public bool Visible { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget WithSize(in int size)
                    {
                        return new global::Test.Widget(this._name__parameter, size);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Widget
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Factory WithVisible(in bool visible)
                    {
                        return new global::Test.Step_2__Test_Factory(this._name, this.Size, visible);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _size__parameter;
                    private readonly bool _visible__parameter;
                    internal Step_2__Test_Factory(in string name, in int size, in bool visible)
                    {
                        this._name__parameter = name;
                        this._size__parameter = size;
                        this._visible__parameter = visible;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Widget.Widget(string name, int size, bool visible).
                    ///
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget CreateWidget()
                    {
                        return new global::Test.Widget(this._name__parameter, this._size__parameter, this._visible__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
