using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Tests for the interaction between CreateMethod.None (ExistingTypeFluentStep) and optional parameters.
/// ExistingTypeFluentStep lacks PropertyFieldStorage, so optional methods may reference non-existent fields.
/// </summary>
public class CreateMethodNoneOptionalTests
{
    /// <summary>
    /// When a constructor uses CreateMethod.None on a partial class and has an optional parameter,
    /// the generated partial class should include a fluent setter method for the optional parameter.
    /// The method returns a new instance with the optional value set.
    /// </summary>
    [Fact]
    internal async Task Should_handle_optional_parameter_on_create_method_none_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class Config
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Config(string name, int timeout = 30)
                {
                    Name = name;
                    Timeout = timeout;
                }

                public string Name { get; set; }
                public int Timeout { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Config WithName(in string name)
                    {
                        return new global::Test.Config(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Config
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Config WithTimeout(in int timeout)
                    {
                        return new global::Test.Config(this.Name, timeout);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// When a constructor uses CreateMethod.None on a partial class and has multiple optional
    /// parameters, the generated partial class should include fluent setter methods for each.
    /// </summary>
    [Fact]
    internal async Task Should_handle_multiple_optional_parameters_on_create_method_none_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class Config
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Config(string name, int timeout = 30, bool verbose = false)
                {
                    Name = name;
                    Timeout = timeout;
                    Verbose = verbose;
                }

                public string Name { get; set; }
                public int Timeout { get; set; }
                public bool Verbose { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Config WithName(in string name)
                    {
                        return new global::Test.Config(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Config
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Config WithTimeout(in int timeout)
                    {
                        return new global::Test.Config(this.Name, timeout, this.Verbose);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Config WithVerbose(in bool verbose)
                    {
                        return new global::Test.Config(this.Name, this.Timeout, verbose);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Variant: CreateMethod.None where ALL parameters are optional (zero required).
    /// The target type itself is the step, with no required parameters to create steps for.
    /// </summary>
    [Fact]
    internal async Task Should_handle_all_optional_parameters_on_create_method_none_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class Config
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Config(string host = "localhost", int port = 8080)
                {
                    Host = host;
                    Port = port;
                }

                public string Host { get; set; }
                public int Port { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithHost(in string host)
                    {
                        return new global::Test.Step_0__Test_Factory(host: host);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithPort(in int port)
                    {
                        return new global::Test.Step_0__Test_Factory(port: port);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Config"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _host__parameter;
                    private readonly int _port__parameter;
                    internal Step_0__Test_Factory(in string host = "localhost", in int port = 8080)
                    {
                        this._host__parameter = host;
                        this._port__parameter = port;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithHost(in string host)
                    {
                        return new global::Test.Step_0__Test_Factory(host, this._port__parameter);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithPort(in int port)
                    {
                        return new global::Test.Step_0__Test_Factory(this._host__parameter, port);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError("CVJG0001")
                        .WithSpan("/0/Test1.cs", 12, 12, 12, 18)
                        .WithArguments("""Config.Config(string host = "localhost", int port = 8080)"""),
                }
            }
        }.RunAsync();
    }
}
