using Microsoft.CodeAnalysis.Testing;
using static Microsoft.CodeAnalysis.DiagnosticSeverity;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;


public class DiagnosticsTests
{
    private const string SourceFile = "Source.cs";

    [Fact]
    internal async Task Given_two_regular_methods_collide_when_and_there_are_no_more_steps_Should_generate_an_ambiguous_constructor_selection_error()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Person
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Person(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }

                public partial class Company
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Company(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 12, 30, 12, 34)
                        .WithArguments("name", "MyNamespace.Person.Person(string)", "WithName", "MyNamespace.Company, MyNamespace.Person"),
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 23, 31, 23, 35)
                        .WithArguments("name", "MyNamespace.Company.Company(string)", "WithName", "MyNamespace.Company, MyNamespace.Person"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Given_a_regular_and_multi_methods_collide_when_they_service_different_different_source_parameter_types_Should_generate_a_step_method_collisions_error()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Person
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Person(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }

                public partial class Company
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Company([MultipleFluentMethods(typeof(Convert))]int? id)
                    {
                        Id = id;
                    }

                    public int? Id { get; }
                }

                public class Convert
                {
                    [FluentMethodTemplate]
                    public static int? WithName(string name)
                    {
                        return int.TryParse(name, out var id) ? id : null;
                    }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Person WithName(in string name)
                    {
                        return new global::MyNamespace.Person(name);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },

                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError("CVJG0001")
                        .WithSpan("Source.cs", 23, 16, 23, 23)
                        .WithArguments("Company.Company(int? id)"),
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Given_that_there_are_no_compatible_parameter_converters_Should_raise_error()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Converj.Generator;
            using System.Linq.Expressions;

            namespace MyNamespace;

            public abstract class BooleanResultBase<T> {}

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), CreateMethod = CreateMethod.None)]
            public readonly partial struct MyTypeB<TModel, TPredicateResult>(
                [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, MyNamespace.BooleanResultBase<string>, string> trueBecause);

            internal class WhenTrueOverloads
            {
                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return whenTrue;
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return _ => whenTrue;
                }
            }
            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError(AllFluentMethodTemplatesIncompatible.Id)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithArguments("System.Func<TModel, MyNamespace.BooleanResultBase<string>, string> trueBecause"),
                    DiagnosticResult
                        .CompilerError(UnreachableConstructor.Id)
                        .WithSpan(SourceFile, 14, 32, 14, 39)
                        .WithArguments("MyTypeB<TModel, TPredicateResult>.MyTypeB(Func<TModel, BooleanResultBase<string>, string> trueBecause)")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Given_that_there_are_ignored_parameter_converters_Should_raise_warning()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Converj.Generator;
            using System.Linq.Expressions;

            namespace MyNamespace;

            public abstract class BooleanResultBase<T> {}

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), CreateMethod = CreateMethod.None)]
            public readonly partial struct MyTypeB<TModel, TPredicateResult>(
                [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, string> trueBecause);

            internal class WhenTrueOverloads
            {
                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TBooleanResult, TNewMetadata> whenTrue)
                {
                    return whenTrue;
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return (model, _) => whenTrue(model);
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return _ => whenTrue;
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Spec
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.MyTypeB{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.MyTypeB<TModel, TPredicateResult> WhenTrue<TModel, TPredicateResult>(in string whenTrue)
                    {
                        return new global::MyNamespace.MyTypeB<TModel, TPredicateResult>(global::MyNamespace.WhenTrueOverloads.WhenTrue<TModel, string>(whenTrue));
                    }
                }
            }
            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    new DiagnosticResult(IncompatibleFluentMethodTemplate.Id, Warning)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithSpan(SourceFile, 20, 64, 20, 72)
                        .WithArguments(
                            "System.Func<TModel, TBooleanResult, TNewMetadata> MyNamespace.WhenTrueOverloads.WhenTrue<TModel, TBooleanResult, TNewMetadata>(System.Func<TModel, TBooleanResult, TNewMetadata> whenTrue)",
                            "System.Func<TModel, string> trueBecause"),
                    new DiagnosticResult(IncompatibleFluentMethodTemplate.Id, Warning)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithSpan(SourceFile, 26, 64, 26, 72)
                        .WithArguments(
                            "System.Func<TModel, TBooleanResult, TNewMetadata> MyNamespace.WhenTrueOverloads.WhenTrue<TModel, TBooleanResult, TNewMetadata>(System.Func<TModel, TNewMetadata> whenTrue)",
                            "System.Func<TModel, string> trueBecause"),
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Spec.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Should_not_generate_unreachable_constructor_error_if_not_all_multiple_fluent_methods_are_not_ignored()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using System.Linq.Expressions;
            using Converj.Generator;

            namespace Test;

            public class BooleanResultBase<T>;

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), CreateMethod = CreateMethod.None)]
            public readonly partial struct ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>(
                Expression<Func<TModel, TPredicateResult>> expression,
                [MultipleFluentMethods(typeof(WhenTrueOverloads))] Func<TModel, BooleanResultBase<string>, string> trueBecause);

            [FluentConstructor(typeof(Spec), CreateMethod = CreateMethod.None)]
            public readonly partial struct ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>(
                Expression<Func<TModel, TPredicateResult>> expression,
                [FluentMethod("WhenTrue")]string trueBecause);

            public readonly partial struct MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>
            {
                [FluentConstructor(typeof(Spec), CreateMethod = CreateMethod.None)]
                public MultiAssertionExplanationExpressionTreePropositionFactory(
                    Expression<Func<TModel, TPredicateResult>> expression,
                    [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, BooleanResultBase<string>, string> trueBecause)
                {
                }
            }

            internal class WhenTrueOverloads
            {

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return (model, _) => whenTrue(model);
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return (_, _) => whenTrue;
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Spec
                {
                    /// <summary>
                    ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Spec<TModel, TPredicateResult> WithExpression<TModel, TPredicateResult>(in global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> expression)
                    {
                        return new global::Test.Step_0__Test_Spec<TModel, TPredicateResult>(expression);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Spec<TModel, TPredicateResult>
                {
                    private readonly global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> _expression__parameter;
                    internal Step_0__Test_Spec(in global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> expression)
                    {
                        this._expression__parameter = expression;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult> WhenTrue(in global::System.Func<TModel, string> whenTrue)
                    {
                        return new global::Test.MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>(this._expression__parameter, global::Test.WhenTrueOverloads.WhenTrue<TModel, global::Test.BooleanResultBase<string>, string>(whenTrue));
                    }

                    /// <summary>
                    ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult> WhenTrue(in string trueBecause)
                    {
                        return new global::Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>(this._expression__parameter, trueBecause);
                    }
                }
            }
            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError(UnreachableConstructor.Id)
                        .WithSpan(SourceFile, 14, 32, 14, 75)
                        .WithArguments(
                            "ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(Expression<Func<TModel, TPredicateResult>> expression, Func<TModel, BooleanResultBase<string>, string> trueBecause)"),
                    DiagnosticResult
                        .CompilerWarning(ContainsSupersededFluentMethodTemplate.Id)
                        .WithSpan(SourceFile, 16, 28, 16, 53)
                        .WithSpan(SourceFile, 21, 38, 21, 49)
                        .WithArguments(
                            "Test.WhenTrueOverloads.WhenTrue<TModel, Test.BooleanResultBase<string>, string>(string whenTrue)",
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause",
                            "Test.ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause)",
                            "the parameter 'string trueBecause' in the constructor 'Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationWithNameExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, string trueBecause)' was used as the basis for the fluent method. Perhaps the ignored method-template can be removed or modified."),
                    new DiagnosticResult(FluentMethodTemplateSuperseded.Id, Info)
                        .WithSpan("Source.cs", 43, 64, 43, 72)
                        .WithArguments(
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> Test.WhenTrueOverloads.WhenTrue<TModel, Test.BooleanResultBase<string>, string>(string whenTrue)",
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause",
                            "Test.ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause)",
                            "string trueBecause",
                            "Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationWithNameExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, string trueBecause)"),

                },
                GeneratedSources =
                {
                (typeof(FluentFactoryGenerator), "Test.Spec.g.cs", expected)
            }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Should_not_generate_unreachable_constructor_error_with_primary_constructors()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public partial class Shape;

            [FluentFactory]
            [FluentConstructor(typeof(Shape))]
            public partial record Square(int Width);
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Shape
                {
                    /// <summary>
                    ///     <seealso cref="Test.Square"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Shape WithWidth(in int width)
                    {
                        return new global::Test.Step_0__Test_Shape(width);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Square"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Shape
                {
                    private readonly int _width__parameter;
                    internal Step_0__Test_Shape(in int width)
                    {
                        this._width__parameter = width;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Square.Square(int Width).
                    ///
                    ///     <seealso cref="Test.Square"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Square CreateSquare()
                    {
                        return new global::Test.Square(this._width__parameter);
                    }
                }
            }
            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Shape.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_when_optional_parameters_cause_ambiguous_fluent_method_chain_with_another_constructor()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Foo
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Foo(string name, int age = 25)
                    {
                        Name = name;
                        Age = age;
                    }

                    public string Name { get; }
                    public int Age { get; }
                }

                public partial class Bar
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Bar(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(OptionalParameterAmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 11, 37, 11, 40)
                        .WithArguments("age", "MyNamespace.Foo.Foo(string, int)", "MyNamespace.Bar.Bar(string)", "MyNamespace.Bar, MyNamespace.Foo"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_when_both_constructors_have_optional_parameters_causing_ambiguous_chain()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Foo
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Foo(string name, int age = 25)
                    {
                        Name = name;
                        Age = age;
                    }

                    public string Name { get; }
                    public int Age { get; }
                }

                public partial class Bar
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Bar(string name, bool active = true)
                    {
                        Name = name;
                        Active = active;
                    }

                    public string Name { get; }
                    public bool Active { get; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(OptionalParameterAmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 11, 37, 11, 40)
                        .WithArguments("age", "MyNamespace.Foo.Foo(string, int)", "MyNamespace.Bar.Bar(string, bool)", "MyNamespace.Bar, MyNamespace.Foo"),
                    DiagnosticResult.CompilerError(OptionalParameterAmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 24, 38, 24, 44)
                        .WithArguments("active", "MyNamespace.Bar.Bar(string, bool)", "MyNamespace.Foo.Foo(string, int)", "MyNamespace.Bar, MyNamespace.Foo"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_report_optional_parameter_ambiguity_when_disambiguated_by_create_verb()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Foo
                {
                    [FluentConstructor(typeof(Factory), CreateVerb = "MakeFoo")]
                    public Foo(string name, int age = 25)
                    {
                        Name = name;
                        Age = age;
                    }

                    public string Name { get; }
                    public int Age { get; }
                }

                public partial class Bar
                {
                    [FluentConstructor(typeof(Factory), CreateVerb = "MakeBar")]
                    public Bar(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.Bar"/>
                    ///     <seealso cref="MyNamespace.Foo"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Step_0__MyNamespace_Factory WithName(in string name)
                    {
                        return new global::MyNamespace.Step_0__MyNamespace_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="MyNamespace.Bar"/>
                ///     <seealso cref="MyNamespace.Foo"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public struct Step_0__MyNamespace_Factory
                {
                    private readonly string _name__parameter;
                    private int _age__parameter;
                    internal Step_0__MyNamespace_Factory(in string name)
                    {
                        this._name__parameter = name;
                        this._age__parameter = 25;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor MyNamespace.Foo.Foo(string name, int age = 25).
                    ///
                    ///     <seealso cref="MyNamespace.Foo"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.Foo MakeFooFoo()
                    {
                        return new global::MyNamespace.Foo(this._name__parameter, this._age__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor MyNamespace.Bar.Bar(string name).
                    ///
                    ///     <seealso cref="MyNamespace.Bar"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.Bar MakeBarBar()
                    {
                        return new global::MyNamespace.Bar(this._name__parameter);
                    }

                    /// <summary>
                    ///     <seealso cref="MyNamespace.Bar"/>
                    ///     <seealso cref="MyNamespace.Foo"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.Step_0__MyNamespace_Factory WithAge(in int age)
                    {
                        this._age__parameter = age;
                        return this;
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_report_optional_parameter_ambiguity_when_same_type()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class MyClass
                {
                    [FluentConstructor(typeof(Factory))]
                    public MyClass(string name, int age = 25)
                    {
                        Name = name;
                        Age = age;
                    }

                    [FluentConstructor(typeof(Factory))]
                    public MyClass(string name)
                    {
                        Name = name;
                        Age = 0;
                    }

                    public string Name { get; }
                    public int Age { get; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.MyClass"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Step_0__MyNamespace_Factory WithName(in string name)
                    {
                        return new global::MyNamespace.Step_0__MyNamespace_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="MyNamespace.MyClass"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public struct Step_0__MyNamespace_Factory
                {
                    private readonly string _name__parameter;
                    private int _age__parameter;
                    internal Step_0__MyNamespace_Factory(in string name)
                    {
                        this._name__parameter = name;
                        this._age__parameter = 25;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor MyNamespace.MyClass.MyClass(string name, int age = 25).
                    ///
                    ///     <seealso cref="MyNamespace.MyClass"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.MyClass CreateMyClass()
                    {
                        return new global::MyNamespace.MyClass(this._name__parameter, this._age__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor MyNamespace.MyClass.MyClass(string name).
                    ///
                    ///     <seealso cref="MyNamespace.MyClass"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.MyClass CreateMyClass()
                    {
                        return new global::MyNamespace.MyClass(this._name__parameter);
                    }

                    /// <summary>
                    ///     <seealso cref="MyNamespace.MyClass"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::MyNamespace.Step_0__MyNamespace_Factory WithAge(in int age)
                    {
                        this._age__parameter = age;
                        return this;
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError("CS0111")
                        .WithSpan("Converj.Generator\\Converj.Generator.FluentFactoryGenerator\\MyNamespace.Factory.g.cs", 49, 44, 49, 57)
                        .WithArguments("CreateMyClass", "MyNamespace.Step_0__MyNamespace_Factory"),
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_custom_step_has_no_storage_for_constructor_parameter()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class MyStep
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public MyStep(
                    [FluentMethod("WithName")]string name,
                    [FluentMethod("WithAge")]int age)
                {
                    Name = name;
                    // age is NOT assigned to any field or property
                }

                public string Name { get; set; }
            }

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(string name, int age, bool active)
                {
                    Name = name;
                    Age = age;
                    Active = active;
                }

                public string Name { get; set; }
                public int Age { get; set; }
                public bool Active { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(UnresolvableCustomStepStorage.Id)
                        .WithSpan(SourceFile, 13, 38, 13, 41)
                        .WithArguments("Test.MyStep", "age")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_warn_when_multi_constructor_step_has_no_storage_for_non_nullable_parameter()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
            public partial record TypeA(int X, int Y);

            public partial record TypeA
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int X, int Y, string Z) : this(X, Y) { }
            }

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(int X, int Y, string Z, int W)
                {
                    this.X = X;
                    this.Y = Y;
                    this.Z = Z;
                    this.W = W;
                }

                public int X { get; set; }
                public int Y { get; set; }
                public string Z { get; set; }
                public int W { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 13, 6, 13, 74)
                        .WithArguments("Test.TypeA", "Test.Factory")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_suppress_generation_when_multi_constructor_step_parameter_is_nullable()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
            public partial record TypeA(int X, int Y);

            public partial record TypeA
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int X, int Y, string? Z) : this(X, Y) { }
            }

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(int X, int Y, string? Z, int W)
                {
                    this.X = X;
                    this.Y = Y;
                    this.Z = Z;
                    this.W = W;
                }

                public int X { get; set; }
                public int Y { get; set; }
                public string? Z { get; set; }
                public int W { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            CompilerDiagnostics = Microsoft.CodeAnalysis.Testing.CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 13, 6, 13, 74)
                        .WithArguments("Test.TypeA", "Test.Factory"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_suppress_generation_when_fluent_storage_resolves_storage_gap()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
            public partial record TypeA(int X, int Y);

            public partial record TypeA
            {
                [FluentStorage]
                public string Z { get; init; }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int X, int Y, string Z) : this(X, Y) { this.Z = Z; }
            }

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(int X, int Y, string Z, int W)
                {
                    this.X = X;
                    this.Y = Y;
                    this.Z = Z;
                    this.W = W;
                }

                public int X { get; set; }
                public int Y { get; set; }
                public string Z { get; set; }
                public int W { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 16, 6, 16, 74)
                        .WithArguments("Test.TypeA", "Test.Factory"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_fluent_storage_property_has_no_getter()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class TypeA
            {
                public int X { get; set; }
                public int Y { get; set; }

                [FluentStorage]
                public string Z { set { } }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int x, int y, string z) { }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(FluentStoragePropertyWithoutGetter.Id)
                        .WithSpan(SourceFile, 14, 19, 14, 20)
                        .WithArguments("Z")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_error_when_duplicate_fluent_storage_mappings_exist()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class TypeA
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int x, int y) { X = x; Y = y; }

                public int X { get; set; }
                public int Y { get; set; }

                [FluentStorage]
                public string Z { get; set; }

                [FluentStorage("Z")]
                public string AnotherZ { get; set; }

                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TypeA(int x, int y, string z) : this(x, y) { }
            }

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(int x, int y, string z, int w)
                {
                    X = x; Y = y; Z = z; W = w;
                }

                public int X { get; set; }
                public int Y { get; set; }
                public string Z { get; set; }
                public int W { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 22, 6, 22, 74)
                        .WithArguments("Test.TypeA", "Test.Factory")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_error_when_type_has_multiple_FluentConstructors_with_factory_level_CreateMethodNone()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory(CreateMethod = CreateMethod.None)]
                public static partial class Factory;

                public partial class Target
                {
                    [FluentConstructor(typeof(Factory))]
                    public Target(int a, int b) { A = a; B = b; }

                    [FluentConstructor(typeof(Factory))]
                    public Target(int b) { B = b; }

                    public int A { get; }
                    public int B { get; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 13, 10, 13, 44)
                        .WithArguments("MyNamespace.Target", "MyNamespace.Factory"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_error_when_type_has_multiple_FluentConstructors_with_per_constructor_CreateMethodNone()
    {
        const string code =
            """
            using Converj.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Target
                {
                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Target(int a, int b) { A = a; B = b; }

                    [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                    public Target(int b) { B = b; }

                    public int A { get; }
                    public int B { get; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MultipleConstructorsWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 13, 10, 13, 78)
                        .WithArguments("MyNamespace.Target", "MyNamespace.Factory"),
                }
            }
        }.RunAsync();
    }

}
