using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class ExtensionMethodTests
{
    [Fact]
    internal async Task Should_generate_extension_method_chain_for_this_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class StringExt;

            public static class StringHelpers
            {
                [FluentTarget(typeof(StringExt))]
                public static string Pad(this string input, int width, char padChar) =>
                    input.PadRight(width, padChar);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class StringExt
                {
                    /// <summary>
                    ///     <seealso cref="Test.StringHelpers"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_StringExt WithWidth(this string input, in int width)
                    {
                        return new global::Test.Step_0__Test_StringExt(input, width);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.StringHelpers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_StringExt
                {
                    private readonly string _input__parameter;
                    private readonly int _width__parameter;
                    internal Step_0__Test_StringExt(in string input, in int width)
                    {
                        this._input__parameter = input;
                        this._width__parameter = width;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.StringHelpers"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_StringExt WithPadChar(in char padChar)
                    {
                        return new global::Test.Step_1__Test_StringExt(this._input__parameter, this._width__parameter, padChar);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.StringHelpers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_StringExt
                {
                    private readonly string _input__parameter;
                    private readonly int _width__parameter;
                    private readonly char _padChar__parameter;
                    internal Step_1__Test_StringExt(in string input, in int width, in char padChar)
                    {
                        this._input__parameter = input;
                        this._width__parameter = width;
                        this._padChar__parameter = padChar;
                    }

                    /// <summary>
                    /// Calls static method string Test.StringHelpers.Pad(string input, int width, char padChar).
                    ///
                    ///     <seealso cref="Test.StringHelpers"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public string Pad()
                    {
                        return global::Test.StringHelpers.Pad(this._input__parameter, this._width__parameter, this._padChar__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.StringExt.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_extension_method_chain_for_This_attribute_on_static_method()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Parsers;

            public static class ParserHelpers
            {
                [FluentTarget(typeof(Parsers))]
                public static int Parse([This] string input, int radix) =>
                    Convert.ToInt32(input, radix);
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Parsers
                {
                    /// <summary>
                    ///     <seealso cref="Test.ParserHelpers"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Parsers WithRadix(this string input, in int radix)
                    {
                        return new global::Test.Step_0__Test_Parsers(input, radix);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.ParserHelpers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Parsers
                {
                    private readonly string _input__parameter;
                    private readonly int _radix__parameter;
                    internal Step_0__Test_Parsers(in string input, in int radix)
                    {
                        this._input__parameter = input;
                        this._radix__parameter = radix;
                    }

                    /// <summary>
                    /// Calls static method int Test.ParserHelpers.Parse(string input, int radix).
                    ///
                    ///     <seealso cref="Test.ParserHelpers"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public int Parse()
                    {
                        return global::Test.ParserHelpers.Parse(this._input__parameter, this._radix__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Parsers.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_info_diagnostic_when_This_attribute_on_extension_method_first_param()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Ext;

            public static class Helpers
            {
                [FluentTarget(typeof(Ext))]
                public static string DoStuff([This] this string input, int value) => input;
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } }
        };

        test.TestState.ExpectedDiagnostics.Add(
            new DiagnosticResult(ThisAttributeTautologous)
                .WithSpan("/0/Test1.cs", 12, 35, 12, 39)
                .WithArguments("input"));

        // Don't verify generated sources — just checking the diagnostic
        test.TestBehaviors |= Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_error_when_This_attribute_on_non_first_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Ext;

            public static class Helpers
            {
                [FluentTarget(typeof(Ext))]
                public static string DoStuff(string input, [This] int value) => input;
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } }
        };

        test.TestState.ExpectedDiagnostics.Add(
            new DiagnosticResult(ThisAttributeNotOnFirstParameter)
                .WithSpan("/0/Test1.cs", 12, 49, 12, 53)
                .WithArguments("value"));

        test.TestBehaviors |= Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_error_when_root_is_not_static_for_extension_target()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public partial class NonStaticRoot;

            public static class Helpers
            {
                [FluentTarget(typeof(NonStaticRoot))]
                public static string DoStuff(this string input, int value) => input;
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } }
        };

        test.TestState.ExpectedDiagnostics.Add(
            new DiagnosticResult(RootMustBeStaticForExtensionTargets)
                .WithSpan("/0/Test1.cs", 6, 1, 7, 36)
                .WithArguments("NonStaticRoot"));

        test.TestBehaviors |= Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_extension_method_chain_for_This_attribute_on_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class WrapperFactory;

            public class Wrapper
            {
                public string Value { get; }
                public int Priority { get; }

                [FluentTarget(typeof(WrapperFactory))]
                public Wrapper([This] string value, int priority)
                {
                    Value = value;
                    Priority = priority;
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class WrapperFactory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Wrapper"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_WrapperFactory WithPriority(this string value, in int priority)
                    {
                        return new global::Test.Step_0__Test_WrapperFactory(value, priority);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Wrapper"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_WrapperFactory
                {
                    private readonly string _value__parameter;
                    private readonly int _priority__parameter;
                    internal Step_0__Test_WrapperFactory(in string value, in int priority)
                    {
                        this._value__parameter = value;
                        this._priority__parameter = priority;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Wrapper.Wrapper(string value, int priority).
                    ///
                    ///     <seealso cref="Test.Wrapper"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Wrapper CreateWrapper()
                    {
                        return new global::Test.Wrapper(this._value__parameter, this._priority__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.WrapperFactory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
