using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class FluentParameterTests
{
    [Fact]
    internal async Task Should_thread_fluent_parameter_field_to_target_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Factory(int wheels)
                {
                    _wheels = wheels;
                }
            }

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_from_factory_with_primary_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory(int wheels)
            {
                [FluentParameter("wheels")]
                private readonly int _wheels = wheels;
            }

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_to_target_with_primary_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Factory(int wheels) { _wheels = wheels; }
            }

            [FluentTarget(typeof(Factory))]
            public class Vehicle(int wheels, string name)
            {
                public int Wheels { get; set; } = wheels;
                public string Name { get; set; } = name;
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_from_factory_property_to_record_target()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                public int Wheels { get; }

                public Factory(int wheels) { Wheels = wheels; }
            }

            [FluentTarget(typeof(Factory))]
            public record Vehicle(int wheels, string Name);
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.Wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string Name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_when_all_target_params_are_pre_satisfied()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory(int wheels, string name)
            {
                [FluentParameter("wheels")]
                private readonly int _wheels = wheels;

                [FluentParameter("name")]
                private readonly string _name = name;
            }

            [FluentTarget(typeof(Factory))]
            public class Vehicle(int wheels, string name)
            {
                public int Wheels { get; set; } = wheels;
                public string Name { get; set; } = name;
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels, this._name);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Theory]
    [InlineData("record")]
    [InlineData("record struct")]
    internal async Task Should_auto_thread_primary_constructor_parameters_without_attribute(string typeKeyword)
    {
        var code =
            $$"""
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial {{typeKeyword}} Factory(int wheels);

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        var expected =
            $$"""
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial {{typeKeyword}} Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_on_record_primary_constructor_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record Factory([FluentParameter("wheels")] int wheels);

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_on_record_struct_primary_constructor_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Factory([FluentParameter("wheels")] int wheels);

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_on_class_primary_constructor_with_explicit_field()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory([FluentParameter("wheels")] int wheels)
            {
                private readonly int _wheels = wheels;
            }

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_backing_field_for_class_primary_constructor_without_explicit_storage()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory([FluentParameter("wheels")] int wheels);

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string name)
                {
                    Wheels = wheels;
                    Name = name;
                }

                public int Wheels { get; set; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    private readonly int _wheels__fluentParameter = wheels;
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels__fluentParameter, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_explicit_fluent_parameter_with_generic_type_parameters()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Container<T>(T scale)
            {
                [FluentParameter("Scale")]
                public T Scale { get; set; } = scale;
            }

            [FluentTarget(typeof(Container<>))]
            public record Widget<T>(T Scale, string Label);
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Container<T>
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Container____<T> WithLabel(in string label)
                    {
                        return new global::Test.Step_0__Test_Container____<T>(this.Scale, label);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Container____<T>
                {
                    private readonly string _label__parameter;
                    private readonly T _scale__parameter;
                    internal Step_0__Test_Container____(in T scale, in string label)
                    {
                        this._scale__parameter = scale;
                        this._label__parameter = label;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Widget&lt;T&gt;.Widget(T Scale, string Label).
                    ///
                    ///     <seealso cref="Test.Widget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget<T> CreateWidget()
                    {
                        return new global::Test.Widget<T>(this._scale__parameter, this._label__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Container____.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_infer_parameter_name_from_property_name_when_no_argument_given()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter]
                public int Wheels { get; }

                public Factory(int wheels) { Wheels = wheels; }
            }

            [FluentTarget(typeof(Factory))]
            public class Vehicle(int wheels, string name)
            {
                public int Wheels { get; set; } = wheels;
                public string Name { get; set; } = name;
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.Wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_infer_parameter_name_from_underscore_prefixed_field_name()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter]
                private readonly int _wheels;

                public Factory(int wheels) { _wheels = wheels; }
            }

            [FluentTarget(typeof(Factory))]
            public class Vehicle(int wheels, string name)
            {
                public int Wheels { get; set; } = wheels;
                public string Name { get; set; } = name;
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_thread_fluent_parameter_for_open_generic_factory_with_inferred_name()
    {
        // Same as the explicit name test but uses [FluentParameter] (no arg) to infer from property name
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Container<T>(T scale)
            {
                [FluentParameter]
                public T Scale { get; set; } = scale;
            }

            [FluentTarget(typeof(Container<>))]
            public record Widget<T>(T Scale, string Label);
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Container<T>
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Container____<T> WithLabel(in string label)
                    {
                        return new global::Test.Step_0__Test_Container____<T>(this.Scale, label);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Container____<T>
                {
                    private readonly string _label__parameter;
                    private readonly T _scale__parameter;
                    internal Step_0__Test_Container____(in T scale, in string label)
                    {
                        this._scale__parameter = scale;
                        this._label__parameter = label;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Widget&lt;T&gt;.Widget(T Scale, string Label).
                    ///
                    ///     <seealso cref="Test.Widget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget<T> CreateWidget()
                    {
                        return new global::Test.Widget<T>(this._scale__parameter, this._label__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Container____.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_infer_parameter_name_with_case_insensitive_matching()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory(int wheels)
            {
                [FluentParameter]
                public int Wheels { get; set; } = wheels;
            }

            [FluentTarget(typeof(Factory))]
            public record Vehicle(int Wheels, string Name);
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(this.Wheels, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string name)
                    {
                        this._wheels__parameter = wheels;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int Wheels, string Name).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Polyfill source needed for the 'required' keyword in test compilations.
    /// </summary>
    private const string RequiredPolyfill =
        """
        namespace System.Runtime.CompilerServices
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property, Inherited = false)]
            internal sealed class RequiredMemberAttribute : Attribute { }
            [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
            internal sealed class CompilerFeatureRequiredAttribute : Attribute
            {
                public CompilerFeatureRequiredAttribute(string featureName) { FeatureName = featureName; }
                public string FeatureName { get; }
                public bool IsOptional { get; set; }
            }
        }
        namespace System.Diagnostics.CodeAnalysis
        {
            [AttributeUsage(AttributeTargets.Constructor)]
            internal sealed class SetsRequiredMembersAttribute : Attribute { }
        }
        """;

    /// <summary>
    /// Issue #3: A [FluentParameter] threads the only constructor parameter 'name',
    /// AND the target type has a required property 'Email'. When all constructor params
    /// are pre-satisfied by threading, the required property step should still be generated
    /// so users can set it before creation.
    /// </summary>
    [Fact]
    internal async Task Should_generate_required_property_step_when_all_constructor_params_are_threaded()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("name")]
                private readonly string _name;

                public Factory(string name)
                {
                    _name = name;
                }
            }

            public class Person
            {
                [FluentTarget(typeof(Factory))]
                public Person(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }

                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_0__Test_Factory(this._name, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_0__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    /// <summary>
    /// Issue #10: Factory has a [FluentParameter] and the target constructor has multi-optional
    /// parameters (2+ optional, 0 additional required beyond threaded). This triggers gateway
    /// step creation via CreateAllOptionalStepsAndGatewayMethods, which runs AFTER
    /// PropagateThreadedParametersToSteps. Gateway steps may not receive threaded parameters.
    /// </summary>
    [Fact]
    internal async Task Should_thread_parameter_to_gateway_steps_for_all_optional_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Factory(int wheels)
                {
                    _wheels = wheels;
                }
            }

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels, string color = "red", int seats = 4)
                {
                    Wheels = wheels;
                    Color = color;
                    Seats = seats;
                }

                public int Wheels { get; set; }
                public string Color { get; set; }
                public int Seats { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string color = "red", int seats = 4).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithColor(in string color)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, color: color);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithSeats(in int seats)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, seats: seats);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _color__parameter;
                    private readonly int _seats__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string color = "red", in int seats = 4)
                    {
                        this._wheels__parameter = wheels;
                        this._color__parameter = color;
                        this._seats__parameter = seats;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithColor(in string color)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels__parameter, color, this._seats__parameter);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithSeats(in int seats)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels__parameter, this._color__parameter, seats);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels, string color = "red", int seats = 4).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter, this._color__parameter, this._seats__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            },
            CompilerDiagnostics = CompilerDiagnostics.None
        }.RunAsync();
    }
}
