using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Issue #14: Gateway methods for all-optional constructors share the same ValueStorage dictionary.
/// If downstream processing mutates it, all gateway methods are affected simultaneously.
/// These tests verify that each gateway method produces correct independent behavior.
/// </summary>
public class GatewayMethodStorageTests
{
    /// <summary>
    /// All-optional constructor with 2 params -- gateway methods share ValueStorage dict.
    /// Both gateway methods should produce step instances that correctly track their parameter
    /// and the generated code must compile.
    /// </summary>
    [Fact]
    internal async Task Should_generate_independent_gateway_methods_for_all_optional_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Settings
            {
                [FluentTarget(typeof(Factory))]
                public Settings(int width = 100, int height = 200)
                {
                    Width = width;
                    Height = height;
                }

                public int Width { get; set; }
                public int Height { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    /// Creates a new instance using constructor Test.Settings.Settings(int width = 100, int height = 200).
                    ///
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Settings CreateSettings()
                    {
                        return new global::Test.Settings();
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithWidth(in int width)
                    {
                        return new global::Test.Step_0__Test_Factory(width: width);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithHeight(in int height)
                    {
                        return new global::Test.Step_0__Test_Factory(height: height);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Settings"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _width__parameter;
                    private readonly int _height__parameter;
                    internal Step_0__Test_Factory(in int width = 100, in int height = 200)
                    {
                        this._width__parameter = width;
                        this._height__parameter = height;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithWidth(in int width)
                    {
                        return new global::Test.Step_0__Test_Factory(width, this._height__parameter);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithHeight(in int height)
                    {
                        return new global::Test.Step_0__Test_Factory(this._width__parameter, height);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Settings.Settings(int width = 100, int height = 200).
                    ///
                    ///     <seealso cref="Test.Settings"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Settings CreateSettings()
                    {
                        return new global::Test.Settings(this._width__parameter, this._height__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
