using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class GenericAttributeTests
{
    [Fact]
    internal async Task Should_generate_when_generic_attribute_applied_to_a_class_constructor_with_a_single_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Builder;

            public class MyBuildTarget
            {
                [FluentTarget<Builder>]
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Builder(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Builder(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_when_mixing_generic_and_non_generic_attributes_on_same_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class BuilderA;

            [FluentRoot]
            public partial class BuilderB;

            [FluentTarget<BuilderA>]
            [FluentTarget(typeof(BuilderB))]
            public class MyBuildTarget
            {
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expectedA =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class BuilderA
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_BuilderA WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_BuilderA(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_BuilderA
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_BuilderA(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        const string expectedB =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class BuilderB
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_BuilderB WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_BuilderB(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_BuilderB
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_BuilderB(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.BuilderA.g.cs", expectedA),
                    (typeof(FluentRootGenerator), "Test.BuilderB.g.cs", expectedB),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_when_generic_attribute_applied_at_type_level()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Builder;

            [FluentTarget<Builder>]
            public class MyBuildTarget
            {
                public MyBuildTarget(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(string name).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
