using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class HashCodeContractTests
{
    private const string SourceFile = "Source.cs";
    /// <summary>
    /// Exercises COMP-03: two build target classes each with a single-parameter constructor where the
    /// parameter types are the same (string) but the [FluentMethod] names differ ("SetValue" vs "WithText").
    ///
    /// FluentMethodParameter.GetHashCode() delegates to FluentType.GetHashCode() only and ignores the Names
    /// set. So both parameters produce the same hash code (same type: string). However,
    /// FluentMethodParameter.Equals() returns false because Names.Overlaps({"SetValue"}, {"WithText"}) = false.
    ///
    /// This exercises the hash collision path in the Trie: same hash bucket, different equality.
    /// The DESIRED output is two distinct factory methods: SetValue and WithText, each returning its
    /// respective build target.
    /// </summary>
    [Fact]
    internal async Task Should_produce_separate_methods_when_same_type_parameters_have_different_fluent_method_names()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class TargetA
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TargetA([FluentMethod("SetValue")] string text)
                {
                    Text = text;
                }

                public string Text { get; }
            }

            public class TargetB
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TargetB([FluentMethod("WithText")] string text)
                {
                    Text = text;
                }

                public string Text { get; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.TargetA SetValue(in string text)
                    {
                        return new global::Test.TargetA(text);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.TargetB WithText(in string text)
                    {
                        return new global::Test.TargetB(text);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// When two constructors from different types produce identical fluent method chains
    /// (same method name and parameter type at every position), the generator cannot
    /// disambiguate them. Instead of producing broken code, it should emit diagnostic
    /// errors on each parameter that participates in the ambiguous chain, identifying
    /// the conflicting types.
    /// </summary>
    [Fact]
    internal async Task Should_report_diagnostic_when_parameters_have_identical_type_name_and_fluent_method_name()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class TargetA
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TargetA(string value)
                {
                    Value = value;
                }

                public string Value { get; }
            }

            public class TargetB
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public TargetB([FluentMethod("WithValue")] string value)
                {
                    Value = value;
                }

                public string Value { get; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 11, 27, 11, 32)
                        .WithArguments("value", "Test.TargetA.TargetA(string)", "WithValue", "Test.TargetA, Test.TargetB"),
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 22, 21, 22, 46)
                        .WithArguments("value", "Test.TargetB.TargetB(string)", "WithValue", "Test.TargetA, Test.TargetB"),
                }
            }
        }.RunAsync();
    }
}
