using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Edge case tests for generic type constraints on FluentConstructor targets (DIAG-02).
/// Tests assert DESIRED correct output — failing tests document generator shortcomings.
/// </summary>
public class InvalidGenericConstraintTests
{
    private const string SourceFile = "Source.cs";

    /// <summary>
    /// Verifies that a valid <c>where T : struct</c> constraint on the build target's generic parameter
    /// is correctly propagated to the generated factory method and step struct. This is a correctness
    /// test: the generator must emit the constraint on both the factory entry-point method and the
    /// generated step struct so that the resulting code compiles.
    /// </summary>
    [Fact]
    internal async Task Should_propagate_struct_constraint_to_generated_factory_method_and_step_struct()
    {
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentRoot]
                public static partial class Factory;

                public class Container<T> where T : struct
                {
                    [FluentTarget(typeof(Factory))]
                    public Container(T value)
                    {
                        Value = value;
                    }

                    public T Value { get; }
                }
            }
            """;

        // The generator should propagate `where T : struct` to the generated WithValue<T> method
        // and to the step struct Step_0__Test_Namespace_Factory<T>.
        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.Container{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_Factory<T> WithValue<T>(in T value)
                        where T : struct
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_Factory<T>(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.Container{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_Factory<T> where T : struct
                {
                    private readonly T _value__parameter;
                    internal Step_0__Test_Namespace_Factory(in T value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.Container&lt;T&gt;.Container(T value).
                    ///
                    ///     <seealso cref="Test.Namespace.Container{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.Container<T> CreateContainer()
                    {
                        return new global::Test.Namespace.Container<T>(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Namespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies the generator does not crash or emit CVJG diagnostics when processing a build target
    /// whose source code contains a C# compiler error (CS0449: mutually exclusive constraints
    /// <c>where T : class, struct</c>). The test expects the C# compiler error in
    /// <c>ExpectedDiagnostics</c> and asserts no CVJG diagnostic is emitted and no
    /// unhandled exception occurs. This directly tests DIAG-02 graceful error handling.
    /// </summary>
    [Fact]
    internal async Task Should_not_crash_or_emit_mffg_diagnostics_when_user_source_has_invalid_constraint_combination()
    {
        // `where T : class, struct` is invalid C# — the compiler will emit CS0449.
        // The generator must not add any CVJG diagnostic on top of this.
        const string source =
            """
            using Converj.Generator;

            namespace Test.Namespace
            {
                [FluentRoot]
                public static partial class Factory;

                public class BrokenConstraint<T> where T : class, struct
                {
                    [FluentTarget(typeof(Factory))]
                    public BrokenConstraint(T value)
                    {
                        Value = value;
                    }

                    public T Value { get; }
                }
            }
            """;

        // The generator DOES produce output even for invalid constraint combinations, forwarding
        // the constraints as-is from the Roslyn symbol. The generated code will also have the
        // invalid `where T : class, struct` constraint — this is the current behavior.
        //
        // Using CompilerDiagnostics.None to suppress all diagnostic checks (both C# compiler errors
        // and any potential CVJG errors) so the test purely validates that the generator does not
        // throw an unhandled exception.
        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test.Namespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Namespace.BrokenConstraint{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Namespace.Step_0__Test_Namespace_Factory<T> WithValue<T>(in T value)
                        where T : class, struct
                    {
                        return new global::Test.Namespace.Step_0__Test_Namespace_Factory<T>(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Namespace.BrokenConstraint{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Namespace_Factory<T> where T : class, struct
                {
                    private readonly T _value__parameter;
                    internal Step_0__Test_Namespace_Factory(in T value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Namespace.BrokenConstraint&lt;T&gt;.BrokenConstraint(T value).
                    ///
                    ///     <seealso cref="Test.Namespace.BrokenConstraint{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Namespace.BrokenConstraint<T> CreateBrokenConstraint()
                    {
                        return new global::Test.Namespace.BrokenConstraint<T>(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, source) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Namespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
