using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class LargeParameterCountTests
{
    /// <summary>
    /// Tests that the generator correctly produces a chained step structure for a constructor with 5 parameters.
    /// Verifies that step numbering, field storage, type qualification, and chaining all scale correctly from 2-4 parameters to 5.
    /// DateTime requires global:: qualification (non-primitive) while int, string, bool, double do not.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_five_parameters()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Factory), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(
                    int id,
                    string name,
                    bool isActive,
                    double score,
                    DateTime createdAt)
                {
                    Id = id;
                    Name = name;
                    IsActive = isActive;
                    Score = score;
                    CreatedAt = createdAt;
                }

                public int Id { get; set; }
                public string Name { get; set; }
                public bool IsActive { get; set; }
                public double Score { get; set; }
                public DateTime CreatedAt { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_0__Test_Factory(id);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _id__parameter;
                    internal Step_0__Test_Factory(in int id)
                    {
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_1__Test_Factory(this._id__parameter, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    internal Step_1__Test_Factory(in int id, in string name)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Factory WithIsActive(in bool isActive)
                    {
                        return new global::Test.Step_2__Test_Factory(this._id__parameter, this._name__parameter, isActive);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    internal Step_2__Test_Factory(in int id, in string name, in bool isActive)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_3__Test_Factory WithScore(in double score)
                    {
                        return new global::Test.Step_3__Test_Factory(this._id__parameter, this._name__parameter, this._isActive__parameter, score);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_3__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    private readonly double _score__parameter;
                    internal Step_3__Test_Factory(in int id, in string name, in bool isActive, in double score)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                        this._score__parameter = score;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithCreatedAt(in global::System.DateTime createdAt)
                    {
                        return new global::Test.MyBuildTarget(this._id__parameter, this._name__parameter, this._isActive__parameter, this._score__parameter, createdAt);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that the generator correctly produces a chained step structure for a constructor with 8 parameters.
    /// Verifies that step numbering scales to Step_0 through Step_6, all primitive types require no global:: prefix.
    /// This is a stress test to confirm the generator handles large parameter counts without issues in naming or generation.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_eight_parameters()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Factory), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(
                    int id,
                    string name,
                    bool isActive,
                    double score,
                    decimal price,
                    long count,
                    float ratio,
                    byte flags)
                {
                    Id = id;
                    Name = name;
                    IsActive = isActive;
                    Score = score;
                    Price = price;
                    Count = count;
                    Ratio = ratio;
                    Flags = flags;
                }

                public int Id { get; set; }
                public string Name { get; set; }
                public bool IsActive { get; set; }
                public double Score { get; set; }
                public decimal Price { get; set; }
                public long Count { get; set; }
                public float Ratio { get; set; }
                public byte Flags { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_0__Test_Factory(id);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _id__parameter;
                    internal Step_0__Test_Factory(in int id)
                    {
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_1__Test_Factory(this._id__parameter, name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    internal Step_1__Test_Factory(in int id, in string name)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Factory WithIsActive(in bool isActive)
                    {
                        return new global::Test.Step_2__Test_Factory(this._id__parameter, this._name__parameter, isActive);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    internal Step_2__Test_Factory(in int id, in string name, in bool isActive)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_3__Test_Factory WithScore(in double score)
                    {
                        return new global::Test.Step_3__Test_Factory(this._id__parameter, this._name__parameter, this._isActive__parameter, score);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_3__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    private readonly double _score__parameter;
                    internal Step_3__Test_Factory(in int id, in string name, in bool isActive, in double score)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                        this._score__parameter = score;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_4__Test_Factory WithPrice(in decimal price)
                    {
                        return new global::Test.Step_4__Test_Factory(this._id__parameter, this._name__parameter, this._isActive__parameter, this._score__parameter, price);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_4__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    private readonly double _score__parameter;
                    private readonly decimal _price__parameter;
                    internal Step_4__Test_Factory(in int id, in string name, in bool isActive, in double score, in decimal price)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                        this._score__parameter = score;
                        this._price__parameter = price;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_5__Test_Factory WithCount(in long count)
                    {
                        return new global::Test.Step_5__Test_Factory(this._id__parameter, this._name__parameter, this._isActive__parameter, this._score__parameter, this._price__parameter, count);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_5__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    private readonly double _score__parameter;
                    private readonly decimal _price__parameter;
                    private readonly long _count__parameter;
                    internal Step_5__Test_Factory(in int id, in string name, in bool isActive, in double score, in decimal price, in long count)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                        this._score__parameter = score;
                        this._price__parameter = price;
                        this._count__parameter = count;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_6__Test_Factory WithRatio(in float ratio)
                    {
                        return new global::Test.Step_6__Test_Factory(this._id__parameter, this._name__parameter, this._isActive__parameter, this._score__parameter, this._price__parameter, this._count__parameter, ratio);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_6__Test_Factory
                {
                    private readonly int _id__parameter;
                    private readonly string _name__parameter;
                    private readonly bool _isActive__parameter;
                    private readonly double _score__parameter;
                    private readonly decimal _price__parameter;
                    private readonly long _count__parameter;
                    private readonly float _ratio__parameter;
                    internal Step_6__Test_Factory(in int id, in string name, in bool isActive, in double score, in decimal price, in long count, in float ratio)
                    {
                        this._id__parameter = id;
                        this._name__parameter = name;
                        this._isActive__parameter = isActive;
                        this._score__parameter = score;
                        this._price__parameter = price;
                        this._count__parameter = count;
                        this._ratio__parameter = ratio;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithFlags(in byte flags)
                    {
                        return new global::Test.MyBuildTarget(this._id__parameter, this._name__parameter, this._isActive__parameter, this._score__parameter, this._price__parameter, this._count__parameter, this._ratio__parameter, flags);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
