using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class NamespaceDisambiguationTests
{
    /// <summary>
    /// Exercises COMP-01: two separate build target classes each with a single-parameter constructor where
    /// the parameter types share the same simple name ("Config") but come from different namespaces
    /// (NamespaceA.Config vs NamespaceB.Config), both pointing at the same factory.
    ///
    /// The generator's FluentParameterComparer uses Type.Name only (not the full namespace), so it would
    /// treat these as equal. However, FluentMethodParameter delegates to FluentType which uses
    /// ToDisplayString() and includes the full namespace. This test asserts the DESIRED correct output
    /// where both types are fully distinguished and produce two separate WithConfig methods.
    /// </summary>
    [Fact]
    internal async Task Should_distinguish_same_named_types_from_different_namespaces_in_multi_constructor_factory()
    {
        const string code =
            """
            using Converj.Generator;

            namespace NamespaceA
            {
                public class Config
                {
                    public string Value { get; set; } = "";
                }
            }

            namespace NamespaceB
            {
                public class Config
                {
                    public int Value { get; set; }
                }
            }

            namespace MyBuilder
            {
                [FluentRoot]
                public static partial class Builder;
            }

            namespace TargetA
            {
                public class ProductA
                {
                    [FluentTarget(typeof(MyBuilder.Builder), TerminalMethod = TerminalMethod.None)]
                    public ProductA(NamespaceA.Config config)
                    {
                        Config = config;
                    }

                    public NamespaceA.Config Config { get; }
                }
            }

            namespace TargetB
            {
                public class ProductB
                {
                    [FluentTarget(typeof(MyBuilder.Builder), TerminalMethod = TerminalMethod.None)]
                    public ProductB(NamespaceB.Config config)
                    {
                        Config = config;
                    }

                    public NamespaceB.Config Config { get; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyBuilder
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="TargetA.ProductA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::TargetA.ProductA WithConfig(in global::NamespaceA.Config config)
                    {
                        return new global::TargetA.ProductA(config);
                    }

                    /// <summary>
                    ///     <seealso cref="TargetB.ProductB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::TargetB.ProductB WithConfig(in global::NamespaceB.Config config)
                    {
                        return new global::TargetB.ProductB(config);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "MyBuilder.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Exercises COMP-01: a single build target class with two constructor parameters whose types
    /// share the same simple name ("Settings") but come from different namespaces
    /// (NamespaceA.Settings vs NamespaceB.Settings).
    ///
    /// This tests whether the step chain correctly preserves full type qualification in the generated
    /// structs when two parameters have the same simple type name but different full type names.
    /// The DESIRED output produces two chained step structs with fully-qualified global:: type references
    /// for each namespace variant.
    /// </summary>
    [Fact]
    internal async Task Should_distinguish_same_named_parameter_types_from_different_namespaces_in_single_constructor()
    {
        const string code =
            """
            using Converj.Generator;

            namespace NamespaceA
            {
                public class Settings
                {
                    public string Name { get; set; } = "";
                }
            }

            namespace NamespaceB
            {
                public class Settings
                {
                    public int Level { get; set; }
                }
            }

            namespace MyBuilder
            {
                [FluentRoot]
                public static partial class Builder;
            }

            namespace Target
            {
                public class Product
                {
                    [FluentTarget(typeof(MyBuilder.Builder), TerminalMethod = TerminalMethod.None)]
                    public Product(NamespaceA.Settings settingsA, NamespaceB.Settings settingsB)
                    {
                        SettingsA = settingsA;
                        SettingsB = settingsB;
                    }

                    public NamespaceA.Settings SettingsA { get; }
                    public NamespaceB.Settings SettingsB { get; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace MyBuilder
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Target.Product"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyBuilder.Step_0__MyBuilder_Builder WithSettingsA(in global::NamespaceA.Settings settingsA)
                    {
                        return new global::MyBuilder.Step_0__MyBuilder_Builder(settingsA);
                    }
                }

                /// <summary>
                ///     <seealso cref="Target.Product"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__MyBuilder_Builder
                {
                    private readonly global::NamespaceA.Settings _settingsA__parameter;
                    internal Step_0__MyBuilder_Builder(in global::NamespaceA.Settings settingsA)
                    {
                        this._settingsA__parameter = settingsA;
                    }

                    /// <summary>
                    ///     <seealso cref="Target.Product"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Target.Product WithSettingsB(in global::NamespaceB.Settings settingsB)
                    {
                        return new global::Target.Product(this._settingsA__parameter, settingsB);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "MyBuilder.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
