using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class PartiallyOpenGenericTests
{
    /// <summary>
    /// Verifies that a Dictionary&lt;string, T&gt; parameter (partially closed — one concrete, one open type
    /// argument) generates a method that only introduces T as a new type parameter.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_a_partially_closed_dictionary_parameter()
    {
        const string code =
            """
            using System.Collections.Generic;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyBuildTarget<T>
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(Dictionary<string, T> value)
                {
                    Value = value;
                }

                public Dictionary<string, T> Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithValue<T>(in global::System.Collections.Generic.Dictionary<string, T> value)
                    {
                        return new global::Test.MyBuildTarget<T>(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that a Func&lt;int, T&gt; parameter (partially closed delegate — one concrete, one open type
    /// argument) generates correct method with fully qualified Func type.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_a_partially_closed_func_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyBuildTarget<T>
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(Func<int, T> selector)
                {
                    Selector = selector;
                }

                public Func<int, T> Selector { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithSelector<T>(in global::System.Func<int, T> selector)
                    {
                        return new global::Test.MyBuildTarget<T>(selector);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that multiple parameters containing partially open generic types (Dictionary&lt;string, T&gt;,
    /// List&lt;int&gt;, and Func&lt;T, bool&gt;) generate a multi-step builder chain correctly, with T shared
    /// across steps and fully qualified concrete types.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_multiple_partially_open_generic_parameters()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyBuildTarget<T>
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(Dictionary<string, T> lookup, List<int> counts, Func<T, bool> predicate)
                {
                    Lookup = lookup;
                    Counts = counts;
                    Predicate = predicate;
                }

                public Dictionary<string, T> Lookup { get; set; }
                public List<int> Counts { get; set; }
                public Func<T, bool> Predicate { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder<T> WithLookup<T>(in global::System.Collections.Generic.Dictionary<string, T> lookup)
                    {
                        return new global::Test.Step_0__Test_Builder<T>(lookup);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder<T>
                {
                    private readonly global::System.Collections.Generic.Dictionary<string, T> _lookup__parameter;
                    internal Step_0__Test_Builder(in global::System.Collections.Generic.Dictionary<string, T> lookup)
                    {
                        this._lookup__parameter = lookup;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Builder<T> WithCounts(in global::System.Collections.Generic.List<int> counts)
                    {
                        return new global::Test.Step_1__Test_Builder<T>(this._lookup__parameter, counts);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Builder<T>
                {
                    private readonly global::System.Collections.Generic.Dictionary<string, T> _lookup__parameter;
                    private readonly global::System.Collections.Generic.List<int> _counts__parameter;
                    internal Step_1__Test_Builder(in global::System.Collections.Generic.Dictionary<string, T> lookup, in global::System.Collections.Generic.List<int> counts)
                    {
                        this._lookup__parameter = lookup;
                        this._counts__parameter = counts;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget<T> WithPredicate(in global::System.Func<T, bool> predicate)
                    {
                        return new global::Test.MyBuildTarget<T>(this._lookup__parameter, this._counts__parameter, predicate);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
