using Converj.Generator;
using Microsoft.CodeAnalysis.Testing;
using VerifyCS = Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

// Record-replay methodology: expected strings captured by running tests with "TO-BE-CAPTURED"
// and copying the verifier's actual output. The test compilation uses global 'using System.Linq'
// (injected by CSharpSourceGeneratorVerifier) so ImmutableArray<T>.ToArray() resolves.
public class PropertyBackedCollectionTests
{
    // ── Task 1: Analyzer only ─────────────────────────────────────────────────

    [Fact]
    internal async Task Property_target_no_diagnostic_and_detected()
    {
        // Task 1: Verifies that [FluentCollectionMethod] on a property does not produce a diagnostic
        // and that the generated output contains the accumulator method (AddTag).
        // Source-gen output assertion is skipped at this stage; full snapshot added in Task 2.
        const string code =
            """
            using System.Collections.Generic;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target() { }

                [FluentCollectionMethod]
                public IList<string> Tags { get; init; } = new List<string>();
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } },
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };

        // No diagnostics expected — the attribute on a property must be valid.
        await test.RunAsync();
    }

    // ── Task 2: Full source-gen output assertions ─────────────────────────────

    [Fact]
    internal async Task Property_accumulator_emits_addX_method()
    {
        // Happy-path: [FluentCollectionMethod] on an init property produces an accumulator step
        // with AddTag and a terminal method using object-initializer assignment { Tags = ... }.
        const string code =
            """
            using System.Collections.Generic;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target() { }

                [FluentCollectionMethod]
                public IList<string> Tags { get; init; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Accumulator_0__Test_Builder BuildTarget()
                    {
                        return new global::Test.Accumulator_0__Test_Builder();
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Accumulator_0__Test_Builder
                {
                    private readonly global::System.Collections.Immutable.ImmutableArray<string> _tags__property;
                    public Accumulator_0__Test_Builder()
                    {
                        this._tags__property = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
                    }

                    private Accumulator_0__Test_Builder(in global::System.Collections.Immutable.ImmutableArray<string> tags)
                    {
                        this._tags__property = tags;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Accumulator_0__Test_Builder AddTag(in string item)
                    {
                        return new global::Test.Accumulator_0__Test_Builder(this._tags__property.Add(item));
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Target CreateTarget()
                    {
                        return new global::Test.Target()
                        {
                            Tags = this._tags__property.ToArray()
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources = { (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected) }
            }
        };

        await test.RunAsync();
    }

    [Fact]
    internal async Task Property_accumulator_terminal_uses_object_initializer()
    {
        // Verifies the terminal method uses { Tags = ... } syntax (not constructor arg).
        // This test exercises the routing through TargetTypeObjectCreationExpression property initializers.
        const string code =
            """
            using System.Collections.Generic;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target(string name) { Name = name; }

                public string Name { get; }

                [FluentCollectionMethod]
                public IList<string> Tags { get; init; }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } },
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };

        await test.RunAsync();
    }

    [Fact]
    internal async Task Property_accumulator_with_FluentMethod_composes()
    {
        // [FluentCollectionMethod] + [FluentMethod] on a property → both AddTag and WithTags emitted.
        const string code =
            """
            using System.Collections.Generic;
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Target
            {
                [FluentTarget(typeof(Builder))]
                public Target() { }

                [FluentCollectionMethod, FluentMethod]
                public IList<string> Tags { get; init; }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState = { Sources = { code } },
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };

        await test.RunAsync();
    }
}
