using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class RequiredPropertyTests
{
    /// <summary>
    /// Polyfill source needed for the 'required' keyword in test compilations.
    /// </summary>
    private const string RequiredPolyfill =
        """
        namespace System.Runtime.CompilerServices
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property, Inherited = false)]
            internal sealed class RequiredMemberAttribute : Attribute { }
            [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
            internal sealed class CompilerFeatureRequiredAttribute : Attribute
            {
                public CompilerFeatureRequiredAttribute(string featureName) { FeatureName = featureName; }
                public string FeatureName { get; }
                public bool IsOptional { get; set; }
            }
        }
        namespace System.Diagnostics.CodeAnalysis
        {
            [AttributeUsage(AttributeTargets.Constructor)]
            internal sealed class SetsRequiredMembersAttribute : Attribute { }
        }
        """;

    [Fact]
    internal async Task Should_generate_required_property_step_after_constructor_params()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class Person
            {
                [FluentConstructor(typeof(Factory))]
                public Person(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }

                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_auto_skip_required_property_when_initialized_by_constructor_param_on_record()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            [FluentConstructor(typeof(Factory))]
            public partial record Person(string Name)
            {
                public required string Email { get; init; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string Name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }
}
