using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class RequiredPropertyTests
{
    /// <summary>
    /// Polyfill source needed for the 'required' keyword in test compilations.
    /// </summary>
    private const string RequiredPolyfill =
        """
        namespace System.Runtime.CompilerServices
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property, Inherited = false)]
            internal sealed class RequiredMemberAttribute : Attribute { }
            [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
            internal sealed class CompilerFeatureRequiredAttribute : Attribute
            {
                public CompilerFeatureRequiredAttribute(string featureName) { FeatureName = featureName; }
                public string FeatureName { get; }
                public bool IsOptional { get; set; }
            }
        }
        namespace System.Diagnostics.CodeAnalysis
        {
            [AttributeUsage(AttributeTargets.Constructor)]
            internal sealed class SetsRequiredMembersAttribute : Attribute { }
        }
        """;

    [Fact]
    internal async Task Should_generate_required_property_step_after_constructor_params()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Person
            {
                [FluentTarget(typeof(Factory))]
                public Person(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }

                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_auto_skip_required_property_when_initialized_by_constructor_param_on_record()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            [FluentTarget(typeof(Factory))]
            public partial record Person(string Name)
            {
                public required string Email { get; init; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string Name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_rename_required_property_method_via_FluentMethod_attribute()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Person
            {
                [FluentTarget(typeof(Factory))]
                public Person(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }

                [FluentMethod("SetEmail")]
                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory SetEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_auto_skip_property_when_constructor_explicitly_assigns_it()
    {
        const string code =
            """
            using Converj.Attributes;
            using System.Diagnostics.CodeAnalysis;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Person
            {
                [FluentTarget(typeof(Factory))]
                [SetsRequiredMembers]
                public Person(string name, string email)
                {
                    Name = name;
                    Email = email;
                }

                public string Name { get; set; }

                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name, string email).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter, this._email__parameter);
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_required_property_steps_for_root_level_creation_method()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Factory(int wheels)
                {
                    _wheels = wheels;
                }
            }

            public class Vehicle
            {
                [FluentTarget(typeof(Factory))]
                public Vehicle(int wheels)
                {
                    Wheels = wheels;
                }

                public int Wheels { get; set; }

                public required string Color { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_0__Test_Factory WithColor(in string color)
                    {
                        return new global::Test.Step_0__Test_Factory(this._wheels, color);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Vehicle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _wheels__parameter;
                    private readonly string _color__parameter;
                    internal Step_0__Test_Factory(in int wheels, in string color)
                    {
                        this._wheels__parameter = wheels;
                        this._color__parameter = color;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Vehicle.Vehicle(int wheels).
                    ///
                    ///     <seealso cref="Test.Vehicle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Vehicle CreateVehicle()
                    {
                        return new global::Test.Vehicle(this._wheels__parameter)
                        {
                            Color = this._color__parameter
                        };
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_optional_fluent_method_property_on_final_step()
    {
        const string code =
            """
            #nullable enable
            using Converj.Attributes;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Person
            {
                [FluentTarget(typeof(Factory))]
                public Person(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }

                public required string Email { get; set; }

                [FluentMethod]
                public string? Nickname { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithEmail(in string email)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, email);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly string _email__parameter;
                    private string? _nickname__parameter;
                    internal Step_1__Test_Factory(in string name, in string email)
                    {
                        this._name__parameter = name;
                        this._email__parameter = email;
                        this._nickname__parameter = null;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter)
                        {
                            Email = this._email__parameter,
                            Nickname = this._nickname__parameter
                        };
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithNickname(in string? nickname)
                    {
                        this._nickname__parameter = nickname;
                        return this;
                    }
                }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code, RequiredPolyfill },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        };
        await test.RunAsync();
    }
}
