using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class RequiredPropertyDiagnosticsTests
{
    private const string SourceFile = "Source.cs";

    private const string RequiredPolyfill =
        """
        namespace System.Runtime.CompilerServices
        {
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property, Inherited = false)]
            internal sealed class RequiredMemberAttribute : Attribute { }
            [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
            internal sealed class CompilerFeatureRequiredAttribute : Attribute
            {
                public CompilerFeatureRequiredAttribute(string featureName) { FeatureName = featureName; }
                public string FeatureName { get; }
                public bool IsOptional { get; set; }
            }
        }
        namespace System.Diagnostics.CodeAnalysis
        {
            [AttributeUsage(AttributeTargets.Constructor)]
            internal sealed class SetsRequiredMembersAttribute : Attribute { }
        }
        """;

    [Fact]
    internal async Task Should_emit_MFFG0038_when_FluentMethod_on_property_without_setter()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class Person
            {
                [FluentConstructor(typeof(Factory))]
                public Person(string name) { Name = name; }
                public string Name { get; set; }

                [FluentMethod]
                public string Nickname { get; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(FluentMethodOnPropertyWithoutSetter.Id)
                        .WithSpan(SourceFile, 15, 19, 15, 27)
                        .WithArguments("Nickname")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_MFFG0039_when_required_property_with_CreateMethod_None()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public partial class Person
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Person(string name) { Name = name; }
                public string Name { get; set; }

                public required string Email { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Person WithName(in string name)
                    {
                        return new global::Test.Person(name);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code), RequiredPolyfill },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError("CS9035")
                        .WithSpan("Converj.Generator\\Converj.Generator.FluentFactoryGenerator\\Test.Factory.g.cs", 14, 24, 14, 43)
                        .WithArguments("Test.Person.Email"),
                    DiagnosticResult.CompilerWarning(FluentMethodPropertyWithCreateMethodNone.Id)
                        .WithSpan(SourceFile, 14, 28, 14, 33)
                        .WithArguments("Email", "Test.Person")
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_MFFG0042_when_FluentMethod_without_name_on_constructor_param()
    {
        const string code =
            """
            using Converj.Attributes;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class Person
            {
                [FluentConstructor(typeof(Factory))]
                public Person([FluentMethod] string name) { Name = name; }
                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Person"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Person.Person(string name).
                    ///
                    ///     <seealso cref="Test.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Person CreatePerson()
                    {
                        return new global::Test.Person(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    new DiagnosticResult(FluentMethodNoEffectOnParameter.Id, DiagnosticSeverity.Info)
                        .WithSpan(SourceFile, 11, 20, 11, 32)
                        .WithArguments("name")
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
