using Microsoft.CodeAnalysis.Testing;
using static Microsoft.CodeAnalysis.DiagnosticSeverity;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class ReturnTypeDiagnosticsTests
{
    private const string SourceFile = "Source.cs";

    [Fact]
    internal async Task Should_report_error_when_target_type_is_not_assignable_to_factory_return_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                public interface IUnrelated { }

                [FluentRoot(ReturnType = typeof(IUnrelated))]
                public static partial class Factory;

                public class MyBuildTarget
                {
                    [FluentTarget(typeof(Factory))]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(ReturnTypeNotAssignable.Id)
                        .WithSpan(SourceFile, 14, 16, 14, 29)
                        .WithArguments("Test.MyBuildTarget", "Test.IUnrelated"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_error_when_target_type_is_not_assignable_to_constructor_return_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                public interface IUnrelated { }

                [FluentRoot]
                public static partial class Factory;

                public class MyBuildTarget
                {
                    [FluentTarget(typeof(Factory), ReturnType = typeof(IUnrelated))]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(ReturnTypeNotAssignable.Id)
                        .WithSpan(SourceFile, 13, 10, 13, 72)
                        .WithArguments("Test.MyBuildTarget", "Test.IUnrelated"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_warning_when_return_type_equals_concrete_target_type_on_factory()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                [FluentRoot(ReturnType = typeof(MyBuildTarget))]
                public static partial class Factory;

                public class MyBuildTarget
                {
                    [FluentTarget(typeof(Factory))]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Factory(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(PointlessReturnType.Id)
                        .WithSpan(SourceFile, 6, 6, 6, 52)
                        .WithArguments("Test.MyBuildTarget"),
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_error_when_return_type_used_with_create_method_none_on_factory()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                public interface IMyInterface { }

                [FluentRoot(ReturnType = typeof(IMyInterface), TerminalMethod = TerminalMethod.None)]
                public static partial class Factory;

                public partial class MyBuildTarget : IMyInterface
                {
                    [FluentTarget(typeof(Factory))]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(ReturnTypeWithNone.Id)
                        .WithSpan(SourceFile, 8, 17, 8, 50)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_error_when_return_type_used_with_create_method_none_on_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                public interface IMyInterface { }

                [FluentRoot]
                public static partial class Factory;

                public partial class MyBuildTarget : IMyInterface
                {
                    [FluentTarget(typeof(Factory), ReturnType = typeof(IMyInterface), TerminalMethod = TerminalMethod.None)]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(ReturnTypeWithNone.Id)
                        .WithSpan(SourceFile, 13, 40, 13, 73)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_report_warning_when_return_type_equals_concrete_target_type_on_constructor()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                [FluentRoot]
                public static partial class Factory;

                public class MyBuildTarget
                {
                    [FluentTarget(typeof(Factory), ReturnType = typeof(MyBuildTarget))]
                    public MyBuildTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Factory(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyBuildTarget.MyBuildTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget CreateMyBuildTarget()
                    {
                        return new global::Test.MyBuildTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(PointlessReturnType.Id)
                        .WithSpan(SourceFile, 11, 10, 11, 75)
                        .WithArguments("Test.MyBuildTarget"),
                }
            }
        }.RunAsync();
    }
}
