namespace Converj.Generator.Tests;

using VerifyCS = CSharpSourceGeneratorVerifier<FluentRootGenerator>;

public class RootTypeTests
{
    [Fact]
    internal async Task Should_generate_for_an_existing_static_partial_class_target_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in int value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_for_an_existing_partial_record_target_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record Builder;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in int value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_for_an_existing_partial_struct_target_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial struct Builder;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in int value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_for_an_existing_partial_record_struct_target_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(in int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in int value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_use_namespace_when_parameter_type_declared_within_current_namespace()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            public class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(in MyParameterValue value)
                {
                    Value = value;
                }

                public MyParameterValue Value { get; set; }
            }

            public record MyParameterValue(int Value)
            {
                public int Value { get; set; } = Value;
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in global::Test.MyParameterValue value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_use_namespace_when_parameter_type_declared_within_current_namespace_using_three_constructors()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            public partial class MyBuildTarget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(in MyParameterValue value1, in MyParameterValue value2, MyParameterValue value3)
                {
                    Value1 = value1;
                    Value2 = value2;
                    Value3 = value3;
                }

                public MyParameterValue Value1 { get; set; }
                public MyParameterValue Value2 { get; set; }
                public MyParameterValue Value3 { get; set; }
            }

            public record MyParameterValue();
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue1(in global::Test.MyParameterValue value1)
                    {
                        return new global::Test.Step_0__Test_Builder(value1);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    internal Step_0__Test_Builder(in global::Test.MyParameterValue value1)
                    {
                        this._value1__parameter = value1;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Builder WithValue2(in global::Test.MyParameterValue value2)
                    {
                        return new global::Test.Step_1__Test_Builder(this._value1__parameter, value2);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    private readonly global::Test.MyParameterValue _value2__parameter;
                    internal Step_1__Test_Builder(in global::Test.MyParameterValue value1, in global::Test.MyParameterValue value2)
                    {
                        this._value1__parameter = value1;
                        this._value2__parameter = value2;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithValue3(in global::Test.MyParameterValue value3)
                    {
                        return new global::Test.MyBuildTarget(this._value1__parameter, this._value2__parameter, value3);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }



    [Fact]
    internal async Task Should_not_use_namespace_when_parameter_as_generic_type_declared_within_current_namespace_using_three_constructor_parameters()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            public partial class MyBuildTarget<T1, T2>
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTarget(in MyParameterValue<T1, T2> value1, in MyParameterValue<T1, T2> value2, MyParameterValue<T1, T2> value3)
                {
                    Value1 = value1;
                    Value2 = value2;
                    Value3 = value3;
                }

                public MyParameterValue<T1, T2> Value1 { get; set; }
                public MyParameterValue<T1, T2> Value2 { get; set; }
                public MyParameterValue<T1, T2> Value3 { get; set; }
            }

            public record MyParameterValue<T1, T2>();
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T1, T2}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder<T1, T2> WithValue1<T1, T2>(in global::Test.MyParameterValue<T1, T2> value1)
                    {
                        return new global::Test.Step_0__Test_Builder<T1, T2>(value1);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget{T1, T2}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder<T1, T2>
                {
                    private readonly global::Test.MyParameterValue<T1, T2> _value1__parameter;
                    internal Step_0__Test_Builder(in global::Test.MyParameterValue<T1, T2> value1)
                    {
                        this._value1__parameter = value1;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T1, T2}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Builder<T1, T2> WithValue2(in global::Test.MyParameterValue<T1, T2> value2)
                    {
                        return new global::Test.Step_1__Test_Builder<T1, T2>(this._value1__parameter, value2);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget{T1, T2}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Builder<T1, T2>
                {
                    private readonly global::Test.MyParameterValue<T1, T2> _value1__parameter;
                    private readonly global::Test.MyParameterValue<T1, T2> _value2__parameter;
                    internal Step_1__Test_Builder(in global::Test.MyParameterValue<T1, T2> value1, in global::Test.MyParameterValue<T1, T2> value2)
                    {
                        this._value1__parameter = value1;
                        this._value2__parameter = value2;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T1, T2}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget<T1, T2> WithValue3(in global::Test.MyParameterValue<T1, T2> value3)
                    {
                        return new global::Test.MyBuildTarget<T1, T2>(this._value1__parameter, this._value2__parameter, value3);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_not_use_namespace_when_parameter_type_declared_within_current_namespace_using_two_constructors()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            public partial class MyBuildTargetA
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTargetA(in MyParameterValue value1, in MyParameterValue value2, MyParameterValue value3, MyParameterValue value4)
                {
                    Value1 = value1;
                    Value2 = value2;
                    Value3 = value3;
                    Value4 = value4;
                }

                public MyParameterValue Value1 { get; set; }
                public MyParameterValue Value2 { get; set; }
                public MyParameterValue Value3 { get; set; }
                public MyParameterValue Value4 { get; set; }
            }

            public partial class MyBuildTargetB
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public MyBuildTargetB(in MyParameterValue value1, in MyParameterValue value2)
                {
                    Value1 = value1;
                    Value2 = value2;
                }

                public MyParameterValue Value1 { get; set; }
                public MyParameterValue Value2 { get; set; }
            }

            public record MyParameterValue();
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    ///     <seealso cref="Test.MyBuildTargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue1(in global::Test.MyParameterValue value1)
                    {
                        return new global::Test.Step_0__Test_Builder(value1);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTargetA"/>
                ///     <seealso cref="Test.MyBuildTargetB"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    internal Step_0__Test_Builder(in global::Test.MyParameterValue value1)
                    {
                        this._value1__parameter = value1;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    ///     <seealso cref="Test.MyBuildTargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTargetB WithValue2(in global::Test.MyParameterValue value2)
                    {
                        return new global::Test.MyBuildTargetB(this._value1__parameter, value2);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyBuildTargetB
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Builder WithValue3(in global::Test.MyParameterValue value3)
                    {
                        return new global::Test.Step_2__Test_Builder(this.Value1, this.Value2, value3);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTargetA"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    private readonly global::Test.MyParameterValue _value2__parameter;
                    private readonly global::Test.MyParameterValue _value3__parameter;
                    internal Step_2__Test_Builder(in global::Test.MyParameterValue value1, in global::Test.MyParameterValue value2, in global::Test.MyParameterValue value3)
                    {
                        this._value1__parameter = value1;
                        this._value2__parameter = value2;
                        this._value3__parameter = value3;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTargetA WithValue4(in global::Test.MyParameterValue value4)
                    {
                        return new global::Test.MyBuildTargetA(this._value1__parameter, this._value2__parameter, this._value3__parameter, value4);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact] public async Task Should_utilize_the_primary_constructor_parameters_of_partial_target_type_when_also_used_as_a_step_type()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial record struct Builder;

            [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
            public partial class MyBuildTargetA(MyParameterValue value1, MyParameterValue value2, MyParameterValue value3, MyParameterValue value4);

            [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
            public partial class MyBuildTargetB(MyParameterValue value1, MyParameterValue value2);

            public record MyParameterValue();
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial record struct Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    ///     <seealso cref="Test.MyBuildTargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue1(in global::Test.MyParameterValue value1)
                    {
                        return new global::Test.Step_0__Test_Builder(value1);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTargetA"/>
                ///     <seealso cref="Test.MyBuildTargetB"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    internal Step_0__Test_Builder(in global::Test.MyParameterValue value1)
                    {
                        this._value1__parameter = value1;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    ///     <seealso cref="Test.MyBuildTargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTargetB WithValue2(in global::Test.MyParameterValue value2)
                    {
                        return new global::Test.MyBuildTargetB(this._value1__parameter, value2);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class MyBuildTargetB
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Builder WithValue3(in global::Test.MyParameterValue value3)
                    {
                        return new global::Test.Step_2__Test_Builder(value1, value2, value3);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyBuildTargetA"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Builder
                {
                    private readonly global::Test.MyParameterValue _value1__parameter;
                    private readonly global::Test.MyParameterValue _value2__parameter;
                    private readonly global::Test.MyParameterValue _value3__parameter;
                    internal Step_2__Test_Builder(in global::Test.MyParameterValue value1, in global::Test.MyParameterValue value2, in global::Test.MyParameterValue value3)
                    {
                        this._value1__parameter = value1;
                        this._value2__parameter = value2;
                        this._value3__parameter = value3;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTargetA WithValue4(in global::Test.MyParameterValue value4)
                    {
                        return new global::Test.MyBuildTargetA(this._value1__parameter, this._value2__parameter, this._value3__parameter, value4);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
