using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Tests for constructor scope and accessibility edge cases.
/// Private or protected constructors with [FluentTarget] cannot be called from generated code.
/// Builder root types missing the partial modifier cannot receive generated methods.
/// </summary>
public class ScopeAndAccessibilityTests
{
    private const string SourceFile = "Source.cs";

    /// <summary>
    /// A private constructor with [FluentTarget] cannot be used in a fluent factory
    /// because the generated code cannot call it. The generator should emit CVJG0012
    /// warning and skip generation for that constructor.
    /// </summary>
    [Fact]
    internal async Task Should_emit_diagnostic_when_FluentTarget_applied_to_private_constructor()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                private MyTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(InaccessibleConstructor.Id)
                        .WithSpan(SourceFile, 11, 13, 11, 21)
                        .WithArguments("Test.MyTarget.MyTarget(int)", "Private")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// A protected constructor with [FluentTarget] cannot be used in a fluent factory
    /// because the generated code cannot call it. The generator should emit CVJG0012
    /// warning and skip generation for that constructor.
    /// </summary>
    [Fact]
    internal async Task Should_emit_diagnostic_when_FluentTarget_applied_to_protected_constructor()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                protected MyTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(InaccessibleConstructor.Id)
                        .WithSpan(SourceFile, 11, 15, 11, 23)
                        .WithArguments("Test.MyTarget.MyTarget(int)", "Protected")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// A public factory with a constructor whose parameter type is internal is an accessibility mismatch.
    /// The generated fluent method would expose the internal type, which is inaccessible to consumers.
    /// The generator should emit CVJG0014 warning.
    /// </summary>
    [Fact]
    internal async Task Should_emit_diagnostic_when_parameter_type_less_accessible_than_factory()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            internal class InternalParam
            {
                public int Value { get; set; }
            }

            public class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                public MyTarget(InternalParam param)
                {
                    Param = param;
                }

                public InternalParam Param { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithParam(in global::Test.InternalParam param)
                    {
                        return new global::Test.Step_0__Test_Builder(param);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly global::Test.InternalParam _param__parameter;
                    internal Step_0__Test_Builder(in global::Test.InternalParam param)
                    {
                        this._param__parameter = param;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyTarget.MyTarget(Test.InternalParam param).
                    ///
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyTarget CreateMyTarget()
                    {
                        return new global::Test.MyTarget(this._param__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            CompilerDiagnostics = Microsoft.CodeAnalysis.Testing.CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources = { (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(InaccessibleParameterType.Id)
                        .WithSpan(SourceFile, 16, 35, 16, 40)
                        .WithArguments("param", "Test.InternalParam", "Test.MyTarget.MyTarget(Test.InternalParam)", "Test.Builder")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// A public factory wrapping an internal target type is an accessibility mismatch.
    /// The generated factory would expose creation of an inaccessible type to public consumers.
    /// The generator should emit CVJG0015 warning.
    /// </summary>
    [Fact]
    internal async Task Should_emit_diagnostic_when_public_root_wraps_internal_target_type()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            internal class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                public MyTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Builder(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Builder(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyTarget.MyTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyTarget CreateMyTarget()
                    {
                        return new global::Test.MyTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            CompilerDiagnostics = Microsoft.CodeAnalysis.Testing.CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources = { (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(AccessibilityMismatch.Id)
                        .WithSpan(SourceFile, 11, 12, 11, 20)
                        .WithArguments("Test.Builder", "Public", "Test.MyTarget", "Internal")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// An internal factory wrapping an internal target type is NOT an accessibility mismatch.
    /// Both are internal so no diagnostic should be emitted.
    /// </summary>
    [Fact]
    internal async Task Should_not_emit_accessibility_mismatch_when_both_internal()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            internal static partial class Builder;

            internal class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                public MyTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                internal static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Builder(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.MyTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                internal readonly struct Step_0__Test_Builder
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Builder(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.MyTarget.MyTarget(int value).
                    ///
                    ///     <seealso cref="Test.MyTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyTarget CreateMyTarget()
                    {
                        return new global::Test.MyTarget(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources = { (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected) }
            }
        }.RunAsync();
    }

    /// <summary>
    /// A nested private class with [FluentTarget] pointing to an outer public factory.
    /// The private nested class is less accessible than the public factory (Private &lt; Public),
    /// so CVJG0015 (accessibility mismatch) should fire.
    /// This test documents the generator's behavior for nested private classes as factory targets.
    /// </summary>
    [Fact]
    internal async Task Should_handle_nested_private_class_as_root_target()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class OuterBuilder;

            public class OuterContainer
            {
                private class NestedTarget
                {
                    [FluentTarget(typeof(OuterBuilder))]
                    public NestedTarget(int value)
                    {
                        Value = value;
                    }

                    public int Value { get; set; }
                }
            }
            """;

        // The generator still produces output for the nested private class (CVJG0015 is a Warning,
        // not an Error). The generated code calls new OuterContainer.NestedTarget(...) which
        // will fail at compile time due to private access — this is a known limitation documented here.
        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class OuterBuilder
                {
                    /// <summary>
                    ///     <seealso cref="Test.OuterContainer.NestedTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_OuterBuilder WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_OuterBuilder(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.OuterContainer.NestedTarget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_OuterBuilder
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_OuterBuilder(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.OuterContainer.NestedTarget.NestedTarget(int value).
                    ///
                    ///     <seealso cref="Test.OuterContainer.NestedTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.OuterContainer.NestedTarget CreateOuterContainer_NestedTarget()
                    {
                        return new global::Test.OuterContainer.NestedTarget(this._value__parameter);
                    }
                }
            }
            """;

        // CVJG0015 fires because the nested private class (Private) is less accessible
        // than the public factory (Public). This documents the generator's behavior:
        // the diagnostic fires as a warning but generation still proceeds (shortcoming).
        await new VerifyCS.Test
        {
            CompilerDiagnostics = Microsoft.CodeAnalysis.Testing.CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources = { (typeof(FluentRootGenerator), "Test.OuterBuilder.g.cs", expected) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerWarning(AccessibilityMismatch.Id)
                        .WithSpan(SourceFile, 13, 16, 13, 28)
                        .WithArguments("Test.OuterBuilder", "Public", "Test.OuterContainer.NestedTarget", "Private")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// A factory root type without the <c>partial</c> modifier cannot receive generated fluent methods.
    /// The generator should emit CVJG0013 error and produce no generated source output.
    /// </summary>
    [Fact]
    internal async Task Should_emit_diagnostic_when_root_type_missing_partial_modifier()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static class Builder;

            public class MyTarget
            {
                [FluentTarget(typeof(Builder))]
                public MyTarget(int value)
                {
                    Value = value;
                }

                public int Value { get; set; }
            }
            """;

        await new VerifyCS.Test
        {
            CompilerDiagnostics = Microsoft.CodeAnalysis.Testing.CompilerDiagnostics.None,
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(MissingPartialModifier.Id)
                        .WithSpan(SourceFile, 6, 21, 6, 28)
                        .WithArguments("Test.Builder")
                }
            }
        }.RunAsync();
    }
}
