using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class StaticMethodTargetTests
{
    private const string SourceFile = "Source.cs";

    [Fact]
    internal async Task Should_warn_when_FluentTarget_applied_to_instance_method()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Creators
            {
                [FluentTarget(typeof(Factory))]
                public Result MakeResult(int value) => new Result { Value = value };
            }

            public class Result
            {
                public int Value { get; set; }
            }
            """;

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
            }
        };

        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerWarning(InstanceMethodTarget.Id)
                .WithSpan("/0/Test1.cs", 11, 6, 11, 35)
                .WithArguments("MakeResult"));

        await test.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_fluent_chain_for_static_method_target()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Result
            {
                public int Value { get; set; }
            }

            public static class Creators
            {
                [FluentTarget(typeof(Factory))]
                public static Result MakeResult(int value) => new Result { Value = value };
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Creators"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in int value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Creators"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly int _value__parameter;
                    internal Step_0__Test_Factory(in int value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Calls static method Test.Result Test.Creators.MakeResult(int value).
                    ///
                    ///     <seealso cref="Test.Creators"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Result MakeResult()
                    {
                        return global::Test.Creators.MakeResult(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
