using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Issue #8: Step indices are assigned across three sequential post-processing phases.
/// If any phase produces unexpected step counts, subsequent indices may collide or have gaps.
/// These tests verify that step struct names have unique, non-colliding indices.
/// </summary>
public class StepIndexStabilityTests
{
    /// <summary>
    /// Builder with multiple target types, some with required properties.
    /// All three index-assignment phases contribute steps. Verify all Step_N__ names are unique.
    /// </summary>
    [Fact]
    internal async Task Should_assign_unique_step_indices_across_multiple_target_types_with_required_properties()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Dog
            {
                [FluentTarget(typeof(Builder))]
                public Dog(string name, int age)
                {
                    Name = name;
                    Age = age;
                }

                public string Name { get; set; }
                public int Age { get; set; }
            }

            public class Cat
            {
                [FluentTarget(typeof(Builder))]
                public Cat(string name, bool indoor)
                {
                    Name = name;
                    Indoor = indoor;
                }

                public string Name { get; set; }
                public bool Indoor { get; set; }
            }

            public class Bird
            {
                [FluentTarget(typeof(Builder))]
                public Bird(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Bird"/>
                    ///     <seealso cref="Test.Cat"/>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Bird"/>
                ///     <seealso cref="Test.Cat"/>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Builder WithAge(in int age)
                    {
                        return new global::Test.Step_1__Test_Builder(this._name__parameter, age);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_2__Test_Builder WithIndoor(in bool indoor)
                    {
                        return new global::Test.Step_2__Test_Builder(this._name__parameter, indoor);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Bird.Bird(string name).
                    ///
                    ///     <seealso cref="Test.Bird"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Bird CreateBird()
                    {
                        return new global::Test.Bird(this._name__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Builder
                {
                    private readonly string _name__parameter;
                    private readonly int _age__parameter;
                    internal Step_1__Test_Builder(in string name, in int age)
                    {
                        this._name__parameter = name;
                        this._age__parameter = age;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name, int age).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog CreateDog()
                    {
                        return new global::Test.Dog(this._name__parameter, this._age__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_2__Test_Builder
                {
                    private readonly string _name__parameter;
                    private readonly bool _indoor__parameter;
                    internal Step_2__Test_Builder(in string name, in bool indoor)
                    {
                        this._name__parameter = name;
                        this._indoor__parameter = indoor;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Cat.Cat(string name, bool indoor).
                    ///
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Cat CreateCat()
                    {
                        return new global::Test.Cat(this._name__parameter, this._indoor__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
