using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

/// <summary>
/// Tests for DistinctBy de-duplication behavior when multiple constructors produce steps
/// with identical KnownConstructorParameters but different creation targets.
/// Issue #9: The DistinctBy(step => step.KnownConstructorParameters) call in FluentModelFactory
/// may silently discard steps that share parameter sequences but differ in creation methods.
/// </summary>
public class StepDeduplicationTests
{
    /// <summary>
    /// Two different target types with identical parameter sequences (string name, int age).
    /// Both should be creatable from the shared step -- DistinctBy must not drop one.
    /// </summary>
    [Fact]
    internal async Task Should_preserve_creation_methods_for_both_types_when_parameter_sequences_match()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Dog
            {
                [FluentTarget(typeof(Factory))]
                public Dog(string name, int age)
                {
                    Name = name;
                    Age = age;
                }

                public string Name { get; set; }
                public int Age { get; set; }
            }

            public class Cat
            {
                [FluentTarget(typeof(Factory))]
                public Cat(string name, int age)
                {
                    Name = name;
                    Age = age;
                }

                public string Name { get; set; }
                public int Age { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithAge(in int age)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, age);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _age__parameter;
                    internal Step_1__Test_Factory(in string name, in int age)
                    {
                        this._name__parameter = name;
                        this._age__parameter = age;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name, int age).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog CreateDog()
                    {
                        return new global::Test.Dog(this._name__parameter, this._age__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Cat.Cat(string name, int age).
                    ///
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Cat CreateCat()
                    {
                        return new global::Test.Cat(this._name__parameter, this._age__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Three different target types with identical single-parameter sequences.
    /// All three should be creatable from the shared step.
    /// </summary>
    [Fact]
    internal async Task Should_preserve_all_three_creation_methods_when_parameter_sequences_match()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Factory;

            public class Alpha
            {
                [FluentTarget(typeof(Factory))]
                public Alpha(string value)
                {
                    Value = value;
                }

                public string Value { get; set; }
            }

            public class Beta
            {
                [FluentTarget(typeof(Factory))]
                public Beta(string value)
                {
                    Value = value;
                }

                public string Value { get; set; }
            }

            public class Gamma
            {
                [FluentTarget(typeof(Factory))]
                public Gamma(string value)
                {
                    Value = value;
                }

                public string Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Alpha"/>
                    ///     <seealso cref="Test.Beta"/>
                    ///     <seealso cref="Test.Gamma"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in string value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Alpha"/>
                ///     <seealso cref="Test.Beta"/>
                ///     <seealso cref="Test.Gamma"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Factory
                {
                    private readonly string _value__parameter;
                    internal Step_0__Test_Factory(in string value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Alpha.Alpha(string value).
                    ///
                    ///     <seealso cref="Test.Alpha"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Alpha CreateAlpha()
                    {
                        return new global::Test.Alpha(this._value__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Beta.Beta(string value).
                    ///
                    ///     <seealso cref="Test.Beta"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Beta CreateBeta()
                    {
                        return new global::Test.Beta(this._value__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Gamma.Gamma(string value).
                    ///
                    ///     <seealso cref="Test.Gamma"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Gamma CreateGamma()
                    {
                        return new global::Test.Gamma(this._value__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
