using Microsoft.CodeAnalysis.Testing;
using static Converj.Generator.Diagnostics.FluentDiagnostics;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class TrieKeyCollisionTests
{
    private const string SourceFile = "Source.cs";

    /// <summary>
    /// Tests that two constructors with identical parameter type sequences but different parameter names
    /// are NOT merged by the Trie, because <c>FluentMethodParameter</c> equality uses <c>Names.Overlaps</c>
    /// and non-overlapping names with the same type are NOT equal in the Trie.
    /// Expected: Builder has both <c>WithName</c> and <c>WithLabel</c> as separate entry points,
    /// each leading to its own step chain.
    /// </summary>
    [Fact]
    internal async Task Given_two_constructors_with_same_type_sequence_but_different_names_Should_generate_separate_entry_points()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class TargetA
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public TargetA(string name, int age)
                {
                    Name = name;
                    Age = age;
                }

                public string Name { get; set; }
                public int Age { get; set; }
            }

            public class TargetB
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public TargetB(string label, int count)
                {
                    Label = label;
                    Count = count;
                }

                public string Label { get; set; }
                public int Count { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Builder(name);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_1__Test_Builder WithLabel(in string label)
                    {
                        return new global::Test.Step_1__Test_Builder(label);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.TargetA"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetA WithAge(in int age)
                    {
                        return new global::Test.TargetA(this._name__parameter, age);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.TargetB"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_1__Test_Builder
                {
                    private readonly string _label__parameter;
                    internal Step_1__Test_Builder(in string label)
                    {
                        this._label__parameter = label;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetB WithCount(in int count)
                    {
                        return new global::Test.TargetB(this._label__parameter, count);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that two constructors targeting the same factory with the same generic parameter name
    /// and same parameter name but different where-clause constraints (struct vs class) emit
    /// CVJG0023 diagnostic because C# cannot overload on generic constraints alone.
    /// </summary>
    [Fact]
    internal async Task Given_two_constructors_with_same_generic_param_but_different_constraints_Should_emit_conflicting_constraints_diagnostic()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class StructContainer<T> where T : struct
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public StructContainer(T value)
                {
                    Value = value;
                }

                public T Value { get; }
            }

            public class ClassContainer<T> where T : class
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public ClassContainer(T value)
                {
                    Value = value;
                }

                public T Value { get; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 11, 30, 11, 35)
                        .WithArguments("value", "Test.StructContainer<T>.StructContainer(T)", "WithValue",
                            "Test.ClassContainer<T>, Test.StructContainer<T>"),
                    DiagnosticResult.CompilerError(ConflictingTypeConstraints.Id)
                        .WithSpan(SourceFile, 11, 30, 11, 35)
                        .WithArguments("value", "Test.StructContainer<T>.StructContainer(T)", "WithValue",
                            "Test.ClassContainer<T>, Test.StructContainer<T>"),
                    DiagnosticResult.CompilerError(AmbiguousFluentMethodChain.Id)
                        .WithSpan(SourceFile, 22, 29, 22, 34)
                        .WithArguments("value", "Test.ClassContainer<T>.ClassContainer(T)", "WithValue",
                            "Test.ClassContainer<T>, Test.StructContainer<T>"),
                    DiagnosticResult.CompilerError(ConflictingTypeConstraints.Id)
                        .WithSpan(SourceFile, 22, 29, 22, 34)
                        .WithArguments("value", "Test.ClassContainer<T>.ClassContainer(T)", "WithValue",
                            "Test.ClassContainer<T>, Test.StructContainer<T>"),
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that two constructors targeting the same factory with the same effective type parameter
    /// name but different interface constraints emit CVJG0023 diagnostic.
    /// </summary>
    [Fact]
    internal async Task Given_two_constructors_with_different_interface_constraints_Should_emit_conflicting_constraints_diagnostic()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public interface IEngineA;
            public interface IEngineB;

            public class CarA<T> where T : IEngineA
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public CarA(T engine, int age)
                {
                    Engine = engine;
                    Age = age;
                }

                public T Engine { get; }
                public int Age { get; }
            }

            public class CarB<T> where T : IEngineB
            {
                [FluentTarget(typeof(Builder))]
                public CarB(T engine)
                {
                    Engine = engine;
                }

                public T Engine { get; }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(ConflictingTypeConstraints.Id)
                        .WithSpan(SourceFile, 14, 19, 14, 25)
                        .WithArguments("engine", "Test.CarA<T>.CarA(T, int)", "WithEngine",
                            "Test.CarA<T>, Test.CarB<T>"),
                    DiagnosticResult.CompilerError(ConflictingTypeConstraints.Id)
                        .WithSpan(SourceFile, 27, 19, 27, 25)
                        .WithArguments("engine", "Test.CarB<T>.CarB(T)", "WithEngine",
                            "Test.CarA<T>, Test.CarB<T>"),
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that two constructors with the same type parameter constraint (but originally
    /// different type parameter names resolved via [As] alias) are correctly merged by the Trie.
    /// This validates that the constraint suffix uses alias-resolved names for constraint type
    /// arguments, so IConstraint&lt;TNum&gt; (where TNum has [As("T")]) matches IConstraint&lt;T&gt;.
    /// </summary>
    [Fact]
    internal async Task Given_two_constructors_with_aliased_type_params_and_same_constraints_Should_merge_correctly()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            public interface IConstraint<T>;

            [FluentRoot(TerminalMethod = TerminalMethod.None)]
            public static partial class Builder;

            public class TargetA<[As("T")]TNum> where TNum : IConstraint<TNum>
            {
                [FluentTarget(typeof(Builder))]
                public TargetA(TNum value, int extra) { Value = value; Extra = extra; }
                public TNum Value { get; }
                public int Extra { get; }
            }

            public class TargetB<T> where T : IConstraint<T>
            {
                [FluentTarget(typeof(Builder))]
                public TargetB(T value, bool flag) { Value = value; Flag = flag; }
                public T Value { get; }
                public bool Flag { get; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA{TNum}"/>
                    ///     <seealso cref="Test.TargetB{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder<T> WithValue<T>(in T value)
                        where T : global::Test.IConstraint<T>
                    {
                        return new global::Test.Step_0__Test_Builder<T>(value);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.TargetA{TNum}"/>
                ///     <seealso cref="Test.TargetB{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder<T> where T : global::Test.IConstraint<T>
                {
                    private readonly T _value__parameter;
                    internal Step_0__Test_Builder(in T value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetA{TNum}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetA<T> WithExtra(in int extra)
                    {
                        return new global::Test.TargetA<T>(this._value__parameter, extra);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetB<T> WithFlag(in bool flag)
                    {
                        return new global::Test.TargetB<T>(this._value__parameter, flag);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that two constructors with a shared parameter prefix are correctly merged by the Trie
    /// at the common node, then branch into separate steps for the diverging parameters.
    /// TargetA: <c>(string name, int age)</c> and TargetB: <c>(string name, bool isActive)</c>
    /// share <c>string name</c> as the first parameter. The Trie merges at <c>WithName</c>,
    /// producing a shared Step_0 with both <c>WithAge</c> and <c>WithIsActive</c> as continuation methods.
    /// </summary>
    [Fact]
    internal async Task Given_two_constructors_with_shared_prefix_Should_merge_at_common_node_and_branch_for_diverging_parameters()
    {
        const string code =
            """
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class TargetA
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public TargetA(string name, int age)
                {
                    Name = name;
                    Age = age;
                }

                public string Name { get; set; }
                public int Age { get; set; }
            }

            public class TargetB
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public TargetB(string name, bool isActive)
                {
                    Name = name;
                    IsActive = isActive;
                }

                public string Name { get; set; }
                public bool IsActive { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.TargetA"/>
                ///     <seealso cref="Test.TargetB"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetA WithAge(in int age)
                    {
                        return new global::Test.TargetA(this._name__parameter, age);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetB WithIsActive(in bool isActive)
                    {
                        return new global::Test.TargetB(this._name__parameter, isActive);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
