using Converj.Generator.Diagnostics;
using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentRootGenerator>;

namespace Converj.Generator.Tests;

public class TypeFirstTests
{
    [Fact]
    internal async Task Should_generate_type_first_entry_method_for_single_constructor_with_one_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Dog
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildDog")]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Dog_0__Test_Builder BuildDog()
                    {
                        return new global::Test.Step_Dog_0__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_0__Test_Builder
                {
                    public Step_Dog_0__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Dog_1__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_Dog_1__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_1__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_Dog_1__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog Create()
                    {
                        return new global::Test.Dog(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_separate_entry_methods_for_different_target_types()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Dog
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildDog")]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }

            public class Cat
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildCat")]
                public Cat(int lives)
                {
                    Lives = lives;
                }

                public int Lives { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Dog_0__Test_Builder BuildDog()
                    {
                        return new global::Test.Step_Dog_0__Test_Builder();
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Cat_2__Test_Builder BuildCat()
                    {
                        return new global::Test.Step_Cat_2__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_0__Test_Builder
                {
                    public Step_Dog_0__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Dog_1__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_Dog_1__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_1__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_Dog_1__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog Create()
                    {
                        return new global::Test.Dog(this._name__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Cat_2__Test_Builder
                {
                    public Step_Cat_2__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Cat_3__Test_Builder WithLives(in int lives)
                    {
                        return new global::Test.Step_Cat_3__Test_Builder(lives);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Cat_3__Test_Builder
                {
                    private readonly int _lives__parameter;
                    internal Step_Cat_3__Test_Builder(in int lives)
                    {
                        this._lives__parameter = lives;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Cat.Cat(int lives).
                    ///
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Cat Create()
                    {
                        return new global::Test.Cat(this._lives__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_merge_generic_and_non_generic_same_name_under_one_entry()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Circle
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildCircle")]
                public Circle(double radius)
                {
                    Radius = radius;
                }

                public double Radius { get; set; }
            }

            public class Circle<T>
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildCircle")]
                public Circle(T radius)
                {
                    Radius = radius;
                }

                public T Radius { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Circle"/>
                    ///     <seealso cref="Test.Circle{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Circle_0__Test_Builder BuildCircle()
                    {
                        return new global::Test.Step_Circle_0__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Circle"/>
                ///     <seealso cref="Test.Circle{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Circle_0__Test_Builder
                {
                    public Step_Circle_0__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Circle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Circle_1__Test_Builder WithRadius(in double radius)
                    {
                        return new global::Test.Step_Circle_1__Test_Builder(radius);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Circle{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Circle_2__Test_Builder<T> WithRadius<T>(in T radius)
                    {
                        return new global::Test.Step_Circle_2__Test_Builder<T>(radius);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Circle"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Circle_1__Test_Builder
                {
                    private readonly double _radius__parameter;
                    internal Step_Circle_1__Test_Builder(in double radius)
                    {
                        this._radius__parameter = radius;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Circle.Circle(double radius).
                    ///
                    ///     <seealso cref="Test.Circle"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Circle Create()
                    {
                        return new global::Test.Circle(this._radius__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Circle{T}"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Circle_2__Test_Builder<T>
                {
                    private readonly T _radius__parameter;
                    internal Step_Circle_2__Test_Builder(in T radius)
                    {
                        this._radius__parameter = radius;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Circle&lt;T&gt;.Circle(T radius).
                    ///
                    ///     <seealso cref="Test.Circle{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Circle<T> Create()
                    {
                        return new global::Test.Circle<T>(this._radius__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_allow_per_constructor_type_first_override()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Dog
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildDog")]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }

            public class Cat
            {
                [FluentTarget(typeof(Builder))]
                public Cat(int lives)
                {
                    Lives = lives;
                }

                public int Lives { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithLives(in int lives)
                    {
                        return new global::Test.Step_0__Test_Builder(lives);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Dog_1__Test_Builder BuildDog()
                    {
                        return new global::Test.Step_Dog_1__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Cat"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly int _lives__parameter;
                    internal Step_0__Test_Builder(in int lives)
                    {
                        this._lives__parameter = lives;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Cat.Cat(int lives).
                    ///
                    ///     <seealso cref="Test.Cat"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Cat CreateCat()
                    {
                        return new global::Test.Cat(this._lives__parameter);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_1__Test_Builder
                {
                    public Step_Dog_1__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Dog_2__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_Dog_2__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_2__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_Dog_2__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog Create()
                    {
                        return new global::Test.Dog(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_use_custom_type_first_verb()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Dog
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("MakeDog")]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Dog_0__Test_Builder MakeDog()
                    {
                        return new global::Test.Step_Dog_0__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_0__Test_Builder
                {
                    public Step_Dog_0__Test_Builder()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Dog_1__Test_Builder WithName(in string name)
                    {
                        return new global::Test.Step_Dog_1__Test_Builder(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_1__Test_Builder
                {
                    private readonly string _name__parameter;
                    internal Step_Dog_1__Test_Builder(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog Create()
                    {
                        return new global::Test.Dog(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_emit_diagnostic_when_type_first_entry_methods_collide()
    {
        const string sourceFile = "Source.cs";

        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test
            {
                [FluentRoot]
                public static partial class Builder;

                namespace A
                {
                    public class Circle
                    {
                        [FluentTarget(typeof(Test.Builder))]
                        [FluentEntryMethod("BuildCircle")]
                        public Circle(double radius)
                        {
                            Radius = radius;
                        }

                        public double Radius { get; set; }
                    }
                }

                namespace B
                {
                    public class Circle
                    {
                        [FluentTarget(typeof(Test.Builder))]
                        [FluentEntryMethod("BuildCircle")]
                        public Circle(int radius)
                        {
                            Radius = radius;
                        }

                        public int Radius { get; set; }
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (sourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError(FluentDiagnostics.AmbiguousEntryMethod.Id)
                        .WithSpan(sourceFile, 13, 14, 13, 48)
                        .WithArguments("BuildCircle", "'Test.A.Circle', 'Test.B.Circle'"),
                    DiagnosticResult
                        .CompilerError(FluentDiagnostics.UnreachableConstructor.Id)
                        .WithSpan(sourceFile, 15, 20, 15, 26)
                        .WithArguments("Circle.Circle(double radius)"),
                    DiagnosticResult
                        .CompilerError(FluentDiagnostics.UnreachableConstructor.Id)
                        .WithSpan(sourceFile, 30, 20, 30, 26)
                        .WithArguments("Circle.Circle(int radius)")
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Issue #4: TypeFirst + multi-optional parameters (0 required, 2+ optional).
    /// CreateAllOptionalStepsAndGatewayMethods is not called for TypeFirst chains,
    /// so gateway methods may be missing. All optional params should still be reachable.
    /// </summary>
    [Fact]
    internal async Task Should_generate_optional_param_access_in_type_first_mode_with_all_optional_params()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public class Config
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildConfig")]
                public Config(string host = "localhost", int port = 8080, bool ssl = false)
                {
                    Host = host;
                    Port = port;
                    Ssl = ssl;
                }

                public string Host { get; set; }
                public int Port { get; set; }
                public bool Ssl { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Config_0__Test_Builder BuildConfig()
                    {
                        return new global::Test.Step_Config_0__Test_Builder();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Config"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public struct Step_Config_0__Test_Builder
                {
                    private string _host__parameter;
                    private int _port__parameter;
                    private bool _ssl__parameter;
                    public Step_Config_0__Test_Builder()
                    {
                        this._host__parameter = "localhost";
                        this._port__parameter = 8080;
                        this._ssl__parameter = false;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Builder WithHost(in string host)
                    {
                        this._host__parameter = host;
                        return this;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Builder WithPort(in int port)
                    {
                        this._port__parameter = port;
                        return this;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Builder WithSsl(in bool ssl)
                    {
                        this._ssl__parameter = ssl;
                        return this;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Config.Config(string host = "localhost", int port = 8080, bool ssl = false).
                    ///
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Config Create()
                    {
                        return new global::Test.Config();
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            },
            CompilerDiagnostics = CompilerDiagnostics.None
        }.RunAsync();
    }

    /// <summary>
    /// Issue #5: TypeFirst + FluentParameter threading.
    /// The threaded parameter should be removed from the type-first chain.
    /// </summary>
    [Fact]
    internal async Task Should_thread_fluent_parameter_in_type_first_mode()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public partial class Builder
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Builder(int wheels)
                {
                    _wheels = wheels;
                }
            }

            public class Car
            {
                [FluentTarget(typeof(Builder))]
                [FluentEntryMethod("BuildCar")]
                public Car(int wheels, string color)
                {
                    Wheels = wheels;
                    Color = color;
                }

                public int Wheels { get; set; }
                public string Color { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Car_0__Test_Builder BuildCar()
                    {
                        return new global::Test.Step_Car_0__Test_Builder(this._wheels);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Car"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Car_0__Test_Builder
                {
                    private readonly int _wheels__parameter;
                    internal Step_Car_0__Test_Builder(in int wheels)
                    {
                        this._wheels__parameter = wheels;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Car_1__Test_Builder WithColor(in string color)
                    {
                        return new global::Test.Step_Car_1__Test_Builder(this._wheels__parameter, color);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Car"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Car_1__Test_Builder
                {
                    private readonly string _color__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_Car_1__Test_Builder(in int wheels, in string color)
                    {
                        this._wheels__parameter = wheels;
                        this._color__parameter = color;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Car.Car(int wheels, string color).
                    ///
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Car Create()
                    {
                        return new global::Test.Car(this._wheels__parameter, this._color__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            },
            CompilerDiagnostics = CompilerDiagnostics.None
        }.RunAsync();
    }

    /// <summary>
    /// Issue #11: TypeFirst + TerminalMethod.None — ExistingTypeFluentStep skipped in
    /// TypeFirst indexing loop. Only RegularFluentStep gets Index/TypeFirstTargetName set.
    /// </summary>
    [Fact]
    internal async Task Should_handle_type_first_with_create_method_none()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentRoot]
            public static partial class Builder;

            public partial class Widget
            {
                [FluentTarget(typeof(Builder), TerminalMethod = TerminalMethod.None)]
                public Widget(string label, int count)
                {
                    Label = label;
                    Count = count;
                }

                public string Label { get; set; }
                public int Count { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Builder
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Builder WithLabel(in string label)
                    {
                        return new global::Test.Step_0__Test_Builder(label);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_0__Test_Builder
                {
                    private readonly string _label__parameter;
                    internal Step_0__Test_Builder(in string label)
                    {
                        this._label__parameter = label;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget WithCount(in int count)
                    {
                        return new global::Test.Widget(this._label__parameter, count);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentRootGenerator), "Test.Builder.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
