using Microsoft.CodeAnalysis.Testing;
using VerifyCS =
    Converj.Generator.Tests.CSharpSourceGeneratorVerifier<Converj.Generator.FluentFactoryGenerator>;

namespace Converj.Generator.Tests;

public class TypeFirstTests
{
    [Fact]
    internal async Task Should_generate_type_first_entry_method_for_single_constructor_with_one_parameter()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            public class Dog
            {
                [FluentConstructor(typeof(Factory))]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Dog_0__Test_Factory BuildDog()
                    {
                        return new global::Test.Step_Dog_0__Test_Factory();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_0__Test_Factory
                {
                    public Step_Dog_0__Test_Factory()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Dog_1__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_Dog_1__Test_Factory(name);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Dog"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Dog_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_Dog_1__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Dog.Dog(string name).
                    ///
                    ///     <seealso cref="Test.Dog"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Dog Create()
                    {
                        return new global::Test.Dog(this._name__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_generate_separate_entry_methods_for_different_target_types()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            public class Dog
            {
                [FluentConstructor(typeof(Factory))]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }

            public class Cat
            {
                [FluentConstructor(typeof(Factory))]
                public Cat(int lives)
                {
                    Lives = lives;
                }

                public int Lives { get; set; }
            }
            """;

        // Verify BuildDog and BuildCat both appear, no parameter-first chain
        var compilation = await RoslynTestHelper.GetGeneratedCompilationAsync(code);
        var generatedSource = RoslynTestHelper.GetGeneratedSource(compilation);

        Assert.Contains("BuildDog", generatedSource);
        Assert.Contains("BuildCat", generatedSource);
        Assert.DoesNotContain("CreateDog", generatedSource);
        Assert.DoesNotContain("CreateCat", generatedSource);
        Assert.Contains("Step_Dog_0", generatedSource);
        Assert.Contains("Step_Cat_", generatedSource);
    }

    [Fact]
    internal async Task Should_merge_generic_and_non_generic_same_name_under_one_entry()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            public class Circle
            {
                [FluentConstructor(typeof(Factory))]
                public Circle(double radius)
                {
                    Radius = radius;
                }

                public double Radius { get; set; }
            }

            public class Circle<T>
            {
                [FluentConstructor(typeof(Factory))]
                public Circle(T radius)
                {
                    Radius = radius;
                }

                public T Radius { get; set; }
            }
            """;

        // Verify BuildCircle is the only entry point (no parameter-first WithRadius root methods)
        // and that both Circle and Circle<T> are reachable through the type-first chain
        var compilation = await RoslynTestHelper.GetGeneratedCompilationAsync(code);
        var generatedSource = RoslynTestHelper.GetGeneratedSource(compilation);

        Assert.Contains("BuildCircle", generatedSource);
        Assert.DoesNotContain("CreateCircle", generatedSource);
        // Both WithRadius(double) and WithRadius<T> should appear on the type-first root step
        Assert.Contains("WithRadius(in double radius)", generatedSource);
        Assert.Contains("WithRadius<T>(in T radius)", generatedSource);
        Assert.Contains("Step_Circle_0", generatedSource);
    }

    [Fact]
    internal async Task Should_allow_per_constructor_type_first_override()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class Dog
            {
                [FluentConstructor(typeof(Factory), BuilderMode = BuilderMode.TypeFirst)]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }

            public class Cat
            {
                [FluentConstructor(typeof(Factory))]
                public Cat(int lives)
                {
                    Lives = lives;
                }

                public int Lives { get; set; }
            }
            """;

        // Dog has TypeFirst enabled at constructor level, Cat does not.
        // Only BuildDog() should appear, not BuildCat().
        // Verify via Roslyn compilation that the generated code compiles and contains BuildDog.
        var compilation = await RoslynTestHelper.GetGeneratedCompilationAsync(code);
        var generatedSource = RoslynTestHelper.GetGeneratedSource(compilation);

        Assert.Contains("BuildDog", generatedSource);
        Assert.DoesNotContain("BuildCat", generatedSource);
    }

    [Fact]
    internal async Task Should_use_custom_type_first_verb()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst, TypeFirstVerb = "Make")]
            public static partial class Factory;

            public class Dog
            {
                [FluentConstructor(typeof(Factory))]
                public Dog(string name)
                {
                    Name = name;
                }

                public string Name { get; set; }
            }
            """;

        // Entry method should be MakeDog() instead of BuildDog()
        var compilation = await RoslynTestHelper.GetGeneratedCompilationAsync(code);
        var generatedSource = RoslynTestHelper.GetGeneratedSource(compilation);

        Assert.Contains("MakeDog", generatedSource);
        Assert.DoesNotContain("BuildDog", generatedSource);
    }

    [Fact]
    internal async Task Should_emit_diagnostic_when_type_first_entry_methods_collide()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            namespace A
            {
                public class Circle
                {
                    [FluentConstructor(typeof(Test.Factory))]
                    public Circle(double radius)
                    {
                        Radius = radius;
                    }

                    public double Radius { get; set; }
                }
            }

            namespace B
            {
                public class Circle
                {
                    [FluentConstructor(typeof(Test.Factory))]
                    public Circle(int radius)
                    {
                        Radius = radius;
                    }

                    public int Radius { get; set; }
                }
            }
            """;

        // Both A.Circle and B.Circle would produce BuildCircle() — should emit diagnostic
        var compilation = await RoslynTestHelper.GetGeneratedCompilationAsync(code);
        var generatedSource = RoslynTestHelper.GetGeneratedSource(compilation);

        // The colliding entry methods should NOT be generated
        Assert.DoesNotContain("BuildCircle", generatedSource);
    }

    /// <summary>
    /// Issue #4: TypeFirst + multi-optional parameters (0 required, 2+ optional).
    /// CreateAllOptionalStepsAndGatewayMethods is not called for TypeFirst chains,
    /// so gateway methods may be missing. All optional params should still be reachable.
    /// </summary>
    [Fact]
    internal async Task Should_generate_optional_param_access_in_type_first_mode_with_all_optional_params()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            public class Config
            {
                [FluentConstructor(typeof(Factory))]
                public Config(string host = "localhost", int port = 8080, bool ssl = false)
                {
                    Host = host;
                    Port = port;
                    Ssl = ssl;
                }

                public string Host { get; set; }
                public int Port { get; set; }
                public bool Ssl { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Config_0__Test_Factory BuildConfig()
                    {
                        return new global::Test.Step_Config_0__Test_Factory();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Config"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public struct Step_Config_0__Test_Factory
                {
                    private string _host__parameter;
                    private int _port__parameter;
                    private bool _ssl__parameter;
                    public Step_Config_0__Test_Factory()
                    {
                        this._host__parameter = "localhost";
                        this._port__parameter = 8080;
                        this._ssl__parameter = false;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Factory WithHost(in string host)
                    {
                        this._host__parameter = host;
                        return this;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Factory WithPort(in int port)
                    {
                        this._port__parameter = port;
                        return this;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Config_0__Test_Factory WithSsl(in bool ssl)
                    {
                        this._ssl__parameter = ssl;
                        return this;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Config.Config(string host = "localhost", int port = 8080, bool ssl = false).
                    ///
                    ///     <seealso cref="Test.Config"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Config Create()
                    {
                        return new global::Test.Config();
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            },
            CompilerDiagnostics = CompilerDiagnostics.None
        }.RunAsync();
    }

    /// <summary>
    /// Issue #5: TypeFirst + FluentParameter threading.
    /// The threaded parameter should be removed from the type-first chain.
    /// </summary>
    [Fact]
    internal async Task Should_thread_fluent_parameter_in_type_first_mode()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public partial class Factory
            {
                [FluentParameter("wheels")]
                private readonly int _wheels;

                public Factory(int wheels)
                {
                    _wheels = wheels;
                }
            }

            public class Car
            {
                [FluentConstructor(typeof(Factory))]
                public Car(int wheels, string color)
                {
                    Wheels = wheels;
                    Color = color;
                }

                public int Wheels { get; set; }
                public string Color { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Car_0__Test_Factory BuildCar()
                    {
                        return new global::Test.Step_Car_0__Test_Factory(this._wheels);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Car"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Car_0__Test_Factory
                {
                    private readonly int _wheels__parameter;
                    internal Step_Car_0__Test_Factory(in int wheels)
                    {
                        this._wheels__parameter = wheels;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Car_1__Test_Factory WithColor(in string color)
                    {
                        return new global::Test.Step_Car_1__Test_Factory(this._wheels__parameter, color);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Car"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Car_1__Test_Factory
                {
                    private readonly string _color__parameter;
                    private readonly int _wheels__parameter;
                    internal Step_Car_1__Test_Factory(in int wheels, in string color)
                    {
                        this._wheels__parameter = wheels;
                        this._color__parameter = color;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Car.Car(int wheels, string color).
                    ///
                    ///     <seealso cref="Test.Car"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Car Create()
                    {
                        return new global::Test.Car(this._wheels__parameter, this._color__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            },
            CompilerDiagnostics = CompilerDiagnostics.None
        }.RunAsync();
    }

    /// <summary>
    /// Issue #11: TypeFirst + CreateMethod.None — ExistingTypeFluentStep skipped in
    /// TypeFirst indexing loop. Only RegularFluentStep gets Index/TypeFirstTargetName set.
    /// </summary>
    [Fact]
    internal async Task Should_handle_type_first_with_create_method_none()
    {
        const string code =
            """
            using System;
            using Converj.Generator;

            namespace Test;

            [FluentFactory(BuilderMode = BuilderMode.TypeFirst)]
            public static partial class Factory;

            public partial class Widget
            {
                [FluentConstructor(typeof(Factory), CreateMethod = CreateMethod.None)]
                public Widget(string label, int count)
                {
                    Label = label;
                    Count = count;
                }

                public string Label { get; set; }
                public int Count { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_Widget_0__Test_Factory BuildWidget()
                    {
                        return new global::Test.Step_Widget_0__Test_Factory();
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Widget_0__Test_Factory
                {
                    public Step_Widget_0__Test_Factory()
                    {
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Widget_1__Test_Factory WithLabel(in string label)
                    {
                        return new global::Test.Step_Widget_1__Test_Factory(label);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Widget_1__Test_Factory
                {
                    private readonly string _label__parameter;
                    internal Step_Widget_1__Test_Factory(in string label)
                    {
                        this._label__parameter = label;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_Widget_2__Test_Factory WithCount(in int count)
                    {
                        return new global::Test.Step_Widget_2__Test_Factory(this._label__parameter, count);
                    }
                }

                /// <summary>
                ///     <seealso cref="Test.Widget"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Converj", "$$VERSION$$")]
                public readonly struct Step_Widget_2__Test_Factory
                {
                    private readonly string _label__parameter;
                    private readonly int _count__parameter;
                    internal Step_Widget_2__Test_Factory(in string label, in int count)
                    {
                        this._label__parameter = label;
                        this._count__parameter = count;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Widget.Widget(string label, int count).
                    ///
                    ///     <seealso cref="Test.Widget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Widget Create()
                    {
                        return new global::Test.Widget(this._label__parameter, this._count__parameter);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
