using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;

public class FluentFactoryGeneratorNullableTests
{
    /// <summary>
    /// Verifies that a single nullable reference type parameter (string?) preserves the nullable
    /// annotation in the generated fluent method signature and step struct.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_a_single_nullable_reference_parameter()
    {
        const string code =
            """
            #nullable enable
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(string? value)
                {
                    Value = value;
                }

                public string? Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget WithValue(in string? value)
                    {
                        return new global::Test.MyBuildTarget(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that a mix of nullable and non-nullable parameters (string?, int, List&lt;string?&gt;)
    /// preserves nullable annotations only where declared while keeping non-nullable types unmodified.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_mixed_nullable_and_non_nullable_parameters()
    {
        const string code =
            """
            #nullable enable
            using System.Collections.Generic;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(string? name, int count, List<string?> items)
                {
                    Name = name;
                    Count = count;
                    Items = items;
                }

                public string? Name { get; set; }
                public int Count { get; set; }
                public List<string?> Items { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string? name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_0__Test_Factory
                {
                    private readonly string? _name__parameter;
                    internal Step_0__Test_Factory(in string? name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithCount(in int count)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, count);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_1__Test_Factory
                {
                    private readonly string? _name__parameter;
                    private readonly int _count__parameter;
                    internal Step_1__Test_Factory(in string? name, in int count)
                    {
                        this._name__parameter = name;
                        this._count__parameter = count;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithItems(in global::System.Collections.Generic.List<string?> items)
                    {
                        return new global::Test.MyBuildTarget(this._name__parameter, this._count__parameter, items);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that a nullable generic type parameter (T?) with a class constraint is correctly
    /// represented in the generated method and step struct type signatures.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_generic_class_constructor_with_a_nullable_type_parameter()
    {
        const string code =
            """
            #nullable enable
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget<T> where T : class
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(T? value)
                {
                    Value = value;
                }

                public T? Value { get; set; }
            }
            """;

        const string expected =
            """
            // <auto-generated/>
            #nullable enable
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithValue<T>(in T? value)
                        where T : class
                    {
                        return new global::Test.MyBuildTarget<T>(value);
                    }
                }
            }
            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
