using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;

public class FluentFactoryGeneratorHashCodeContractTests
{
    /// <summary>
    /// Exercises COMP-03: two build target classes each with a single-parameter constructor where the
    /// parameter types are the same (string) but the [FluentMethod] names differ ("SetValue" vs "WithText").
    ///
    /// FluentMethodParameter.GetHashCode() delegates to FluentType.GetHashCode() only and ignores the Names
    /// set. So both parameters produce the same hash code (same type: string). However,
    /// FluentMethodParameter.Equals() returns false because Names.Overlaps({"SetValue"}, {"WithText"}) = false.
    ///
    /// This exercises the hash collision path in the Trie: same hash bucket, different equality.
    /// The DESIRED output is two distinct factory methods: SetValue and WithText, each returning its
    /// respective build target.
    /// </summary>
    [Fact]
    internal async Task Should_produce_separate_methods_when_same_type_parameters_have_different_fluent_method_names()
    {
        const string code =
            """
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class TargetA
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public TargetA([FluentMethod("SetValue")] string text)
                {
                    Text = text;
                }

                public string Text { get; }
            }

            public class TargetB
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public TargetB([FluentMethod("WithText")] string text)
                {
                    Text = text;
                }

                public string Text { get; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.TargetA SetValue(in string text)
                    {
                        return new global::Test.TargetA(text);
                    }

                    /// <summary>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.TargetB WithText(in string text)
                    {
                        return new global::Test.TargetB(text);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Exercises COMP-03: two build target classes each with a single-parameter constructor where the
    /// parameter type (string), parameter name (value), and [FluentMethod] name ("WithValue") are all
    /// identical — making these truly equal FluentMethodParameters that must produce the same hash code.
    ///
    /// FluentMethodParameter.Equals() returns true because:
    ///   - FluentType.Equals() is true (same type: string)
    ///   - Names.Overlaps({"WithValue"}, {"WithValue"}) is true
    ///
    /// This exercises the Trie merge path where two constructor sequences are identical at every node.
    /// The DESIRED output merges these into a single WithValue method that serves both target types.
    /// Since both constructors have the same single parameter, the merged factory method must be able
    /// to construct both TargetA and TargetB from one call — which the generator achieves by emitting
    /// two separate factory methods (one per target) when the final steps diverge at the leaf.
    /// </summary>
    [Fact]
    internal async Task Should_merge_methods_when_parameters_have_identical_type_name_and_fluent_method_name()
    {
        const string code =
            """
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class TargetA
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public TargetA([FluentMethod("WithValue")] string value)
                {
                    Value = value;
                }

                public string Value { get; }
            }

            public class TargetB
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public TargetB([FluentMethod("WithValue")] string value)
                {
                    Value = value;
                }

                public string Value { get; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.TargetA"/>
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithValue(in string value)
                    {
                        return new global::Test.Step_0__Test_Factory(value);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.TargetA"/>
                ///     <seealso cref="Test.TargetB"/>
                /// </summary>
                public struct Step_0__Test_Factory
                {
                    private readonly string _value__parameter;
                    internal Step_0__Test_Factory(in string value)
                    {
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.TargetA.TargetA(string value).
                    ///
                    ///     <seealso cref="Test.TargetA"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetA CreateTargetA()
                    {
                        return new global::Test.TargetA(this._value__parameter);
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.TargetB.TargetB(string value).
                    ///
                    ///     <seealso cref="Test.TargetB"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.TargetB CreateTargetB()
                    {
                        return new global::Test.TargetB(this._value__parameter);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
