using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;

public class FluentFactoryGeneratorRecordVariationTests
{
#if NET6_0_OR_GREATER

    /// <summary>
    /// Tests that the generator uses the explicit constructor parameters when a record has both positional parameters
    /// (synthesized primary constructor) and an explicit constructor annotated with [FluentConstructor].
    /// The generator should use the 3-parameter explicit constructor (name, age, email) rather than
    /// the 2-parameter synthesized one from the positional parameters.
    /// </summary>
    [Fact]
    internal async Task Should_generate_from_explicit_constructor_when_record_has_both_positional_and_explicit_constructor()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public record MyBuildTarget(string Name, int Age)
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(string name, int age, string email) : this(name, age)
                {
                    Email = email;
                }

                public string Email { get; init; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithAge(in int age)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, age);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _age__parameter;
                    internal Step_1__Test_Factory(in string name, in int age)
                    {
                        this._name__parameter = name;
                        this._age__parameter = age;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithEmail(in string email)
                    {
                        return new global::Test.MyBuildTarget(this._name__parameter, this._age__parameter, email);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that the generator treats a record with only an explicit constructor (no positional parameters)
    /// the same as a regular class constructor. The record has no synthesized primary constructor from
    /// positional parameters, so the [FluentConstructor]-annotated explicit constructor is the only one.
    /// </summary>
    [Fact]
    internal async Task Should_generate_standard_fluent_chain_when_record_has_only_explicit_constructor()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public record MyBuildTarget
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(int id, string value)
                {
                    Id = id;
                    Value = value;
                }

                public int Id { get; init; }
                public string Value { get; init; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithId(in int id)
                    {
                        return new global::Test.Step_0__Test_Factory(id);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_0__Test_Factory
                {
                    private readonly int _id__parameter;
                    internal Step_0__Test_Factory(in int id)
                    {
                        this._id__parameter = id;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithValue(in string value)
                    {
                        return new global::Test.MyBuildTarget(this._id__parameter, value);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Tests that the generator handles a record that mixes positional parameters with explicit additional members.
    /// The record has one positional parameter (Name) but an explicit constructor annotated with [FluentConstructor]
    /// that takes 3 parameters (name, priority, isEnabled). The generator should produce a fluent chain
    /// for the full 3-parameter explicit constructor, not just the 1-parameter positional one.
    /// </summary>
    [Fact]
    internal async Task Should_generate_from_explicit_constructor_when_record_mixes_positional_and_explicit_members()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public record MyBuildTarget(string Name)
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(string name, int priority, bool isEnabled) : this(name)
                {
                    Priority = priority;
                    IsEnabled = isEnabled;
                }

                public int Priority { get; init; }
                public bool IsEnabled { get; init; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Factory WithName(in string name)
                    {
                        return new global::Test.Step_0__Test_Factory(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_0__Test_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__Test_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Step_1__Test_Factory WithPriority(in int priority)
                    {
                        return new global::Test.Step_1__Test_Factory(this._name__parameter, priority);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.MyBuildTarget"/>
                /// </summary>
                public struct Step_1__Test_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _priority__parameter;
                    internal Step_1__Test_Factory(in string name, in int priority)
                    {
                        this._name__parameter = name;
                        this._priority__parameter = priority;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MyBuildTarget WithIsEnabled(in bool isEnabled)
                    {
                        return new global::Test.MyBuildTarget(this._name__parameter, this._priority__parameter, isEnabled);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

#endif
}
