using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;

public class FluentFactoryGeneratorGenericArrayTests
{
    /// <summary>
    /// Verifies that a simple generic array parameter (T[]) generates correct fluent method and step
    /// struct using array syntax in the type signature.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_a_generic_array_parameter()
    {
        const string code =
            """
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget<T>
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(T[] values)
                {
                    Values = values;
                }

                public T[] Values { get; set; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithValues<T>(in T[] values)
                    {
                        return new global::Test.MyBuildTarget<T>(values);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that an array of a constructed generic type (List&lt;T&gt;[]) generates correct fluent
    /// method with fully qualified element type and proper array syntax.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_an_array_of_generic_type_parameter()
    {
        const string code =
            """
            using System.Collections.Generic;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget<T>
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(List<T>[] values)
                {
                    Values = values;
                }

                public List<T>[] Values { get; set; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithValues<T>(in global::System.Collections.Generic.List<T>[] values)
                    {
                        return new global::Test.MyBuildTarget<T>(values);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    /// <summary>
    /// Verifies that a jagged array of generic type (T[][]) generates correct fluent method
    /// with double array suffix in the type signature.
    /// </summary>
    [Fact]
    internal async Task Should_generate_when_applied_to_a_class_constructor_with_a_jagged_generic_array_parameter()
    {
        const string code =
            """
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public static partial class Factory;

            public class MyBuildTarget<T>
            {
                [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                public MyBuildTarget(T[][] values)
                {
                    Values = values;
                }

                public T[][] Values { get; set; }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="Test.MyBuildTarget{T}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.MyBuildTarget<T> WithValues<T>(in T[][] values)
                    {
                        return new global::Test.MyBuildTarget<T>(values);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
