using Microsoft.CodeAnalysis.Testing;
using static Microsoft.CodeAnalysis.DiagnosticSeverity;
using static Motiv.FluentFactory.Generator.FluentFactoryGenerator;
using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;


public class FluentFactoryDiagnosticsTests
{
    private const string SourceFile = "Source.cs";

    [Fact]
    internal async Task Given_two_regular_methods_collide_when_and_there_are_no_more_steps_Should_generate_an_ambiguous_constructor_selection_error()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Person
                {
                    [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                    public Person(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }

                public partial class Company
                {
                    [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                    public Company(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }
            """;

        const string expected =
            """
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.Company"/>
                    ///     <seealso cref="MyNamespace.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Company WithName(in string name)
                    {
                        return new global::MyNamespace.Company(name);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(UnreachableConstructor.Id)
                        .WithSpan("Source.cs", 12, 16, 12, 22)
                        .WithArguments("Person.Person(string name)")
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Given_a_regular_and_multi_methods_collide_when_they_service_different_different_source_parameter_types_Should_generate_a_step_method_collisions_error()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace MyNamespace
            {
                [FluentFactory]
                public static partial class Factory;

                public partial class Person
                {
                    [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                    public Person(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }

                public partial class Company
                {
                    [FluentConstructor(typeof(Factory), Options = FluentOptions.NoCreateMethod)]
                    public Company([MultipleFluentMethods(typeof(Convert))]int? id)
                    {
                        Id = id;
                    }

                    public int? Id { get; }
                }

                public class Convert
                {
                    [FluentMethodTemplate]
                    public static int? WithName(string name)
                    {
                        return int.TryParse(name, out var id) ? id : null;
                    }
                }
            }
            """;

        const string expected =
            """
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.Person"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.Person WithName(in string name)
                    {
                        return new global::MyNamespace.Person(name);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },

                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError("MFFG0001")
                        .WithSpan("Source.cs", 23, 16, 23, 23)
                        .WithArguments("Company.Company(int? id)"),
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Given_that_there_are_no_compatible_parameter_converters_Should_raise_error()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Motiv.FluentFactory.Generator;
            using System.Linq.Expressions;

            namespace MyNamespace;

            public abstract class BooleanResultBase<T> {}

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), Options = FluentOptions.NoCreateMethod)]
            public readonly partial struct MyTypeB<TModel, TPredicateResult>(
                [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, MyNamespace.BooleanResultBase<string>, string> trueBecause);

            internal class WhenTrueOverloads
            {
                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return whenTrue;
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return _ => whenTrue;
                }
            }
            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError(AllFluentMethodTemplatesIncompatible.Id)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithArguments("System.Func<TModel, MyNamespace.BooleanResultBase<string>, string> trueBecause"),
                    DiagnosticResult
                        .CompilerError(UnreachableConstructor.Id)
                        .WithSpan(SourceFile, 14, 32, 14, 39)
                        .WithArguments("MyTypeB<TModel, TPredicateResult>.MyTypeB(Func<TModel, BooleanResultBase<string>, string> trueBecause)")
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Given_that_there_are_ignored_parameter_converters_Should_raise_warning()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Motiv.FluentFactory.Generator;
            using System.Linq.Expressions;

            namespace MyNamespace;

            public abstract class BooleanResultBase<T> {}

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), Options = FluentOptions.NoCreateMethod)]
            public readonly partial struct MyTypeB<TModel, TPredicateResult>(
                [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, string> trueBecause);

            internal class WhenTrueOverloads
            {
                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TBooleanResult, TNewMetadata> whenTrue)
                {
                    return whenTrue;
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return (model, _) => whenTrue(model);
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TNewMetadata> WhenTrue<TModel, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return _ => whenTrue;
                }
            }
            """;

        const string expected =
            """
            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Spec
                {
                    /// <summary>
                    ///     <seealso cref="MyNamespace.MyTypeB{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::MyNamespace.MyTypeB<TModel, TPredicateResult> WhenTrue<TModel, TPredicateResult>(in string whenTrue)
                    {
                        return new global::MyNamespace.MyTypeB<TModel, TPredicateResult>(global::MyNamespace.WhenTrueOverloads.WhenTrue<TModel, string>(whenTrue));
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    new DiagnosticResult(IncompatibleFluentMethodTemplate.Id, Warning)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithSpan(SourceFile, 20, 64, 20, 72)
                        .WithArguments(
                            "System.Func<TModel, TBooleanResult, TNewMetadata> MyNamespace.WhenTrueOverloads.WhenTrue<TModel, TBooleanResult, TNewMetadata>(System.Func<TModel, TBooleanResult, TNewMetadata> whenTrue)",
                            "System.Func<TModel, string> trueBecause"),
                    new DiagnosticResult(IncompatibleFluentMethodTemplate.Id, Warning)
                        .WithSpan(SourceFile, 15, 28, 15, 53)
                        .WithSpan(SourceFile, 26, 64, 26, 72)
                        .WithArguments(
                            "System.Func<TModel, TBooleanResult, TNewMetadata> MyNamespace.WhenTrueOverloads.WhenTrue<TModel, TBooleanResult, TNewMetadata>(System.Func<TModel, TNewMetadata> whenTrue)",
                            "System.Func<TModel, string> trueBecause"),
                },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "MyNamespace.Spec.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Should_not_generate_unreachable_constructor_error_if_not_all_multiple_fluent_methods_are_not_ignored()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using System.Linq.Expressions;
            using Motiv.FluentFactory.Generator;

            namespace Test;

            public class BooleanResultBase<T>;

            [FluentFactory]
            public static partial class Spec;

            [FluentConstructor(typeof(Spec), Options = FluentOptions.NoCreateMethod)]
            public readonly partial struct ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>(
                Expression<Func<TModel, TPredicateResult>> expression,
                [MultipleFluentMethods(typeof(WhenTrueOverloads))] Func<TModel, BooleanResultBase<string>, string> trueBecause);

            [FluentConstructor(typeof(Spec), Options = FluentOptions.NoCreateMethod)]
            public readonly partial struct ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>(
                Expression<Func<TModel, TPredicateResult>> expression,
                [FluentMethod("WhenTrue")]string trueBecause);

            public readonly partial struct MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>
            {
                [FluentConstructor(typeof(Spec), Options = FluentOptions.NoCreateMethod)]
                public MultiAssertionExplanationExpressionTreePropositionFactory(
                    Expression<Func<TModel, TPredicateResult>> expression,
                    [MultipleFluentMethods(typeof(WhenTrueOverloads))]Func<TModel, BooleanResultBase<string>, string> trueBecause)
                {
                }
            }

            internal class WhenTrueOverloads
            {

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(Func<TModel, TNewMetadata> whenTrue)
                {
                    return (model, _) => whenTrue(model);
                }

                [FluentMethodTemplate]
                internal static Func<TModel, TBooleanResult, TNewMetadata> WhenTrue<TModel, TBooleanResult, TNewMetadata>(TNewMetadata whenTrue)
                {
                    return (_, _) => whenTrue;
                }
            }
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Spec
                {
                    /// <summary>
                    ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Spec<TModel, TPredicateResult> WithExpression<TModel, TPredicateResult>(in global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> expression)
                    {
                        return new global::Test.Step_0__Test_Spec<TModel, TPredicateResult>(expression);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                /// </summary>
                public struct Step_0__Test_Spec<TModel, TPredicateResult>
                {
                    private readonly global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> _expression__parameter;
                    internal Step_0__Test_Spec(in global::System.Linq.Expressions.Expression<global::System.Func<TModel, TPredicateResult>> expression)
                    {
                        this._expression__parameter = expression;
                    }

                    /// <summary>
                    ///     <seealso cref="Test.ExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    ///     <seealso cref="Test.MultiAssertionExplanationExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult> WhenTrue(in global::System.Func<TModel, string> whenTrue)
                    {
                        return new global::Test.MultiAssertionExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>(this._expression__parameter, global::Test.WhenTrueOverloads.WhenTrue<TModel, global::Test.BooleanResultBase<string>, string>(whenTrue));
                    }

                    /// <summary>
                    ///     <seealso cref="Test.ExplanationWithNameExpressionTreePropositionFactory{TModel, TPredicateResult}"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult> WhenTrue(in string trueBecause)
                    {
                        return new global::Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>(this._expression__parameter, trueBecause);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                ExpectedDiagnostics =
                {
                    DiagnosticResult
                        .CompilerError(UnreachableConstructor.Id)
                        .WithSpan(SourceFile, 14, 32, 14, 75)
                        .WithArguments(
                            "ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(Expression<Func<TModel, TPredicateResult>> expression, Func<TModel, BooleanResultBase<string>, string> trueBecause)"),
                    DiagnosticResult
                        .CompilerWarning(ContainsSupersededFluentMethodTemplate.Id)
                        .WithSpan(SourceFile, 16, 28, 16, 53)
                        .WithSpan(SourceFile, 21, 38, 21, 49)
                        .WithArguments(
                            "Test.WhenTrueOverloads.WhenTrue<TModel, Test.BooleanResultBase<string>, string>(string whenTrue)",
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause",
                            "Test.ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause)",
                            "the parameter 'string trueBecause' in the constructor 'Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationWithNameExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, string trueBecause)' was used as the basis for the fluent method. Perhaps the ignored method-template can be removed or modified."),
                    new DiagnosticResult(FluentMethodTemplateSuperseded.Id, Info)
                        .WithSpan("Source.cs", 43, 64, 43, 72)
                        .WithArguments(
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> Test.WhenTrueOverloads.WhenTrue<TModel, Test.BooleanResultBase<string>, string>(string whenTrue)",
                            "System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause",
                            "Test.ExplanationExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, System.Func<TModel, Test.BooleanResultBase<string>, string> trueBecause)",
                            "string trueBecause",
                            "Test.ExplanationWithNameExpressionTreePropositionFactory<TModel, TPredicateResult>.ExplanationWithNameExpressionTreePropositionFactory(System.Linq.Expressions.Expression<System.Func<TModel, TPredicateResult>> expression, string trueBecause)"),

                },
                GeneratedSources =
                {
                (typeof(FluentFactoryGenerator), "Test.Spec.g.cs", expected)
            }
            }
        }.RunAsync();
    }

    [Fact]
    internal Task Should_not_generate_unreachable_constructor_error_with_primary_constructors()
    {
        const string code =
            """
            using Motiv.FluentFactory.Generator;

            namespace Test;

            [FluentFactory]
            public partial class Shape;

            [FluentFactory]
            [FluentConstructor(typeof(Shape))]
            public partial record Square(int Width);
            """;

        const string expected =
            """
            namespace Test
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public partial class Shape
                {
                    /// <summary>
                    ///     <seealso cref="Test.Square"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::Test.Step_0__Test_Shape WithWidth(in int width)
                    {
                        return new global::Test.Step_0__Test_Shape(width);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="Test.Square"/>
                /// </summary>
                public struct Step_0__Test_Shape
                {
                    private readonly int _width__parameter;
                    internal Step_0__Test_Shape(in int width)
                    {
                        this._width__parameter = width;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor Test.Square.Square(int Width).
                    ///
                    ///     <seealso cref="Test.Square"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::Test.Square Create()
                    {
                        return new global::Test.Square(this._width__parameter);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        return new VerifyCS.Test
        {
            TestState =
            {
                Sources = { (SourceFile, code) },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "Test.Shape.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
