using VerifyCS =
    Motiv.FluentFactory.Generator.Tests.CSharpSourceGeneratorVerifier<Motiv.FluentFactory.Generator.FluentFactoryGenerator>;

namespace Motiv.FluentFactory.Generator.Tests;

public class NamespaceConflictTests
{
    [Fact]
    internal async Task Should_compile_when_consumer_defines_type_named_String()
    {
        const string code =
            """
            using System;
            using Motiv.FluentFactory.Generator;

            namespace ConflictTest;

            public class String { }

            [FluentFactory]
            public static partial class Factory;

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(string name, int value)
                {
                    Name = name;
                    Value = value;
                }
                public string Name { get; }
                public int Value { get; }
            }
            """;

        const string expected =
            """
            namespace ConflictTest
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="ConflictTest.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::ConflictTest.Step_0__ConflictTest_Factory WithName(in string name)
                    {
                        return new global::ConflictTest.Step_0__ConflictTest_Factory(name);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="ConflictTest.Target"/>
                /// </summary>
                public struct Step_0__ConflictTest_Factory
                {
                    private readonly string _name__parameter;
                    internal Step_0__ConflictTest_Factory(in string name)
                    {
                        this._name__parameter = name;
                    }

                    /// <summary>
                    ///     <seealso cref="ConflictTest.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::ConflictTest.Step_1__ConflictTest_Factory WithValue(in int value)
                    {
                        return new global::ConflictTest.Step_1__ConflictTest_Factory(this._name__parameter, value);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="ConflictTest.Target"/>
                /// </summary>
                public struct Step_1__ConflictTest_Factory
                {
                    private readonly string _name__parameter;
                    private readonly int _value__parameter;
                    internal Step_1__ConflictTest_Factory(in string name, in int value)
                    {
                        this._name__parameter = name;
                        this._value__parameter = value;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor ConflictTest.Target.Target(string name, int value).
                    ///
                    ///     <seealso cref="ConflictTest.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::ConflictTest.Target Create()
                    {
                        return new global::ConflictTest.Target(this._name__parameter, this._value__parameter);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "ConflictTest.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }

    [Fact]
    internal async Task Should_compile_when_consumer_defines_type_named_List()
    {
        const string code =
            """
            using System;
            using System.Collections.Generic;
            using Motiv.FluentFactory.Generator;

            namespace ConflictTest;

            public class List { }

            [FluentFactory]
            public static partial class Factory;

            public class Target
            {
                [FluentConstructor(typeof(Factory))]
                public Target(List<string> items)
                {
                    Items = items;
                }
                public List<string> Items { get; }
            }
            """;

        const string expected =
            """
            namespace ConflictTest
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                public static partial class Factory
                {
                    /// <summary>
                    ///     <seealso cref="ConflictTest.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::ConflictTest.Step_0__ConflictTest_Factory WithItems(in global::System.Collections.Generic.List<string> items)
                    {
                        return new global::ConflictTest.Step_0__ConflictTest_Factory(items);
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Motiv.FluentFactory", "1.0.0.0")]
                /// <summary>
                ///     <seealso cref="ConflictTest.Target"/>
                /// </summary>
                public struct Step_0__ConflictTest_Factory
                {
                    private readonly global::System.Collections.Generic.List<string> _items__parameter;
                    internal Step_0__ConflictTest_Factory(in global::System.Collections.Generic.List<string> items)
                    {
                        this._items__parameter = items;
                    }

                    /// <summary>
                    /// Creates a new instance using constructor ConflictTest.Target.Target(System.Collections.Generic.List&lt;string&gt; items).
                    ///
                    ///     <seealso cref="ConflictTest.Target"/>
                    /// </summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::ConflictTest.Target Create()
                    {
                        return new global::ConflictTest.Target(this._items__parameter);
                    }
                }
            }// <auto-generated/>
            #nullable enable

            """;

        await new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(FluentFactoryGenerator), "ConflictTest.Factory.g.cs", expected)
                }
            }
        }.RunAsync();
    }
}
